name: ichess
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  chess: ^0.8.1
  chess_vectors_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  dartchess: ^0.9.2
  file_picker: ^8.1.4
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  lottie: ^3.1.3
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  socket_io_client: ^3.0.0
  stockfish: ^1.5.0
  wp_chessboard: ^0.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: 'CAMPUS'
      fonts:
        - asset: 'assets/fonts/CAMPUS PERSONAL USE.ttf'
    - family: 'The Amazing Spider-Man'
      fonts:
        - asset: 'assets/fonts/The Amazing Spider-Man.ttf'
    - family: 'Komigo3D-Regular'
      fonts:
        - asset: 'assets/fonts/Komigo3D-Regular.ttf'
  
  assets:
    - assets/icons/
    - assets/animations/
    - assets/pieces/
    - assets/pieces/android/
    - assets/pieces/aquarium/
    - assets/pieces/aquariumsteel/
    - assets/pieces/aquariumwood/
    - assets/pieces/fragmented/
    - assets/pieces/internet/
    - assets/pieces/military/
    - assets/manuals/
    - assets/manuals.json
    - assets/sounds/

icons_launcher:
  image_path: "assets/icons/icon-a.png"
  # dart run icons_launcher:create
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
