name: ichess
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  chess: ^0.8.1
  cupertino_icons: ^1.0.8
  dartchess: ^0.9.2
  file_picker: ^8.1.4
  fl_chart: ^0.69.0
  flu_wake_lock: ^0.0.2
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  lottie: ^3.1.3
  path_provider: ^2.1.5
  popover: ^0.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  socket_io_client: ^3.0.0
  stockfish: ^1.5.0
  wp_chessboard: ^0.0.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  freezed: ^2.5.8
  icons_launcher: ^3.0.0
  json_serializable: ^6.9.2
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: "ZCOOLXiaoWei"
      fonts:
        - asset: "assets/fonts/ZCOOLXiaoWei-Regular.ttf"
    
    - family: "NotoSerif"
      fonts:
        - asset: "assets/fonts/NotoSerif-Thin.ttf"
          weight: 100
        - asset: "assets/fonts/NotoSerif-ExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/NotoSerif-Light.ttf"
          weight: 300
        - asset: "assets/fonts/NotoSerif-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/NotoSerif-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/NotoSerif-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/NotoSerif-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/NotoSerif-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/NotoSerif-Black.ttf"
          weight: 900

  assets:
    - assets/icons/
    - assets/animations/
    - assets/pieces/
    - assets/pieces/android/
    - assets/pieces/aquarium/
    - assets/pieces/aquariumsteel/
    - assets/pieces/aquariumwood/
    - assets/pieces/fragmented/
    - assets/pieces/internet/
    - assets/pieces/military/
    - assets/games/
    - assets/games.json
    - assets/sounds/

icons_launcher:
  image_path: "assets/icons/icon-a.png"
  # dart run icons_launcher:create
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
