wget http://www.chess88.net/pgn/fidegrandsw21.pgn
wget http://www.chess88.net/pgn/fidegrandsww21.pgn
wget http://www.chess88.net/pgn/wch21.pgn
wget http://www.chess88.net/pgn/wchcand22.pgn
wget http://www.chess88.net/pgn/ftxroadp22.pgn
wget http://www.chess88.net/pgn/ftxroadko22.pgn
wget http://www.chess88.net/pgn/olym22.pgn
wget http://www.chess88.net/pgn/olymw22.pgn
wget http://www.chess88.net/pgn/fidewomcanda22.pgn
wget http://www.chess88.net/pgn/fidewomcandb22.pgn
wget http://www.chess88.net/pgn/wteamgpa22.pgn
wget http://www.chess88.net/pgn/wteamgpb22.pgn
wget http://www.chess88.net/pgn/wteamgpl22.pgn
wget http://www.chess88.net/pgn/wchwcandf23.pgn
wget http://www.chess88.net/pgn/wch23.pgn
wget http://www.chess88.net/pgn/wchr23.pgn
wget http://www.chess88.net/pgn/superbetcl23.pgn
wget http://www.chess88.net/pgn/capmemel23.pgn
wget http://www.chess88.net/pgn/sige23.pgn
wget http://www.chess88.net/pgn/nicosiawgp23.pgn
wget http://www.chess88.net/pgn/warsawrap23.pgn
wget http://www.chess88.net/pgn/sharjmast23.pgn
wget http://www.chess88.net/pgn/warsawbli23.pgn
wget http://www.chess88.net/pgn/chisl23.pgn
wget http://www.chess88.net/pgn/wbliw19.pgn
wget http://www.chess88.net/pgn/norway23.pgn
wget http://www.chess88.net/pgn/norwayb23.pgn
wget http://www.chess88.net/pgn/norwaya23.pgn
wget http://www.chess88.net/pgn/dubaiop23.pgn
wget http://www.chess88.net/pgn/cairnscup23.pgn
wget http://www.chess88.net/pgn/wchw23.pgn
wget http://www.chess88.net/pgn/zagrebrap23.pgn
wget http://www.chess88.net/pgn/zagrebbli23.pgn
wget http://www.chess88.net/pgn/wcup23.pgn
wget http://www.chess88.net/pgn/wcupw23.pgn
wget http://www.chess88.net/pgn/cairnscup20.pgn
wget http://www.chess88.net/pgn/praguemast20.pgn
wget http://www.chess88.net/pgn/aeroflotopa20.pgn
wget http://www.chess88.net/pgn/praguechall20.pgn
wget http://www.chess88.net/pgn/lauswgp20.pgn
wget http://www.chess88.net/pgn/praguemasttb20.pgn
wget http://www.chess88.net/pgn/wchcand20.pgn
wget http://www.chess88.net/pgn/onlinenatcupp20.pgn
wget http://www.chess88.net/pgn/norway20.pgn
wget http://www.chess88.net/pgn/onlinenatcupf20.pgn
wget http://www.chess88.net/pgn/chchn21.pgn
wget http://www.chess88.net/pgn/gibwgp21.pgn
wget http://www.chess88.net/pgn/chchnw21.pgn
wget http://www.chess88.net/pgn/gelfandchall21.pgn
wget http://www.chess88.net/pgn/superbetcl21.pgn
wget http://www.chess88.net/pgn/snow26.pgn
wget http://www.chess88.net/pgn/best02.pgn
wget http://www.chess88.net/pgn/best03.pgn
wget http://www.chess88.net/pgn/best04.pgn
wget http://www.chess88.net/pgn
wget http://www.chess88.net/pgn/bosnia00.pgn
wget http://www.chess88.net/pgn/amber2001.pgn
wget http://www.chess88.net/pgn/Corus.pgn
wget http://www.chess88.net/pgn/korch70.pgn
wget http://www.chess88.net/pgn/linares2001.pgn
wget http://www.chess88.net/pgn/korch70ko.pgn
wget http://www.chess88.net/pgn/rdall.pgn
wget http://www.chess88.net/pgn/bgncomp.pgn
wget http://www.chess88.net/pgn/uschn.pgn
wget http://www.chess88.net/pgn/brainwcc.pgn
wget http://www.chess88.net/pgn/merida01.pgn
wget http://www.chess88.net/pgn/chrus2001.pgn
wget http://www.chess88.net/pgn/capa2001.pgn
wget http://www.chess88.net/pgn/mirabal.pgn
wget http://www.chess88.net/pgn/bosnia01.pgn
wget http://www.chess88.net/pgn/borow.pgn
wget http://www.chess88.net/pgn/astana01.pgn
wget http://www.chess88.net/pgn/golden.pgn
wget http://www.chess88.net/pgn/eutch01.pgn
wget http://www.chess88.net/pgn/sufe01.pgn
wget http://www.chess88.net/pgn/zt2401.pgn
wget http://www.chess88.net/pgn/leon01.pgn
wget http://www.chess88.net/pgn/mayor.pgn
wget http://www.chess88.net/pgn/smart.pgn
wget http://www.chess88.net/pgn/chned.pgn
wget http://www.chess88.net/pgn/2cheur.pgn
wget http://www.chess88.net/pgn/chnedp.pgn
wget http://www.chess88.net/pgn/2cheurp.pgn
wget http://www.chess88.net/pgn/chnedw.pgn
wget http://www.chess88.net/pgn/mainzduel.pgn
wget http://www.chess88.net/pgn/tomskop.pgn
wget http://www.chess88.net/pgn/mainzduelp.pgn
wget http://www.chess88.net/pgn/czn01.pgn
wget http://www.chess88.net/pgn/mainzpf.pgn
wget http://www.chess88.net/pgn/northsea.pgn
wget http://www.chess88.net/pgn/clichy01.pgn
wget http://www.chess88.net/pgn/swym01.pgn
wget http://www.chess88.net/pgn/vidmar01.pgn
wget http://www.chess88.net/pgn/chbel.pgn
wget http://www.chess88.net/pgn/dort01.pgn
wget http://www.chess88.net/pgn/Chafrica.pgn
wget http://www.chess88.net/pgn/Chnrus01.pgn
wget http://www.chess88.net/pgn/Ukr01ch.pgn
wget http://www.chess88.net/pgn/9thaswe.pgn
wget http://www.chess88.net/pgn/Eurais.pgn
wget http://www.chess88.net/pgn/Najmem01.pgn
wget http://www.chess88.net/pgn/Ecc01.pgn
wget http://www.chess88.net/pgn/iceland2001.pgn
wget http://www.chess88.net/pgn/Kazan01.pgn
wget http://www.chess88.net/pgn/Essent01.pgn
wget http://www.chess88.net/pgn/Tchesp.pgn
wget http://www.chess88.net/pgn/enrotel01.pgn
wget http://www.chess88.net/pgn/prem01.pgn
wget http://www.chess88.net/pgn/Govukr.pgn
wget http://www.chess88.net/pgn/pamp01.pgn
wget http://www.chess88.net/pgn/Smart01.pgn
wget http://www.chess88.net/pgn/reggio01.pgn
wget http://www.chess88.net/pgn/wtc01.pgn
wget http://www.chess88.net/pgn/shoste.pgn
wget http://www.chess88.net/pgn/chusa02.pgn
wget http://www.chess88.net/pgn/wijk02b.pgn
wget http://www.chess88.net/pgn/chusa02p.pgn
wget http://www.chess88.net/pgn/berma02.pgn
wget http://www.chess88.net/pgn/wcc2001.pgn
wget http://www.chess88.net/pgn/bermb02.pgn
wget http://www.chess88.net/pgn/fidechf02.pgn
wget http://www.chess88.net/pgn/aeroflot02.pgn
wget http://www.chess88.net/pgn/wijk02.pgn
wget http://www.chess88.net/pgn/morso02.pgn
wget http://www.chess88.net/pgn/ksu02.pgn
wget http://www.chess88.net/pgn/Amber02.pgn
wget http://www.chess88.net/pgn/petrov.pgn
wget http://www.chess88.net/pgn/Gulko02.pgn
wget http://www.chess88.net/pgn/rebwely02.pgn
wget http://www.chess88.net/pgn/goodr.pgn
wget http://www.chess88.net/pgn/nao02.pgn
wget http://www.chess88.net/pgn/chcub02.pgn
wget http://www.chess88.net/pgn/linares02.pgn
wget http://www.chess88.net/pgn/chden02.pgn
wget http://www.chess88.net/pgn/redbus02.pgn
wget http://www.chess88.net/pgn/spbm75.pgn
wget http://www.chess88.net/pgn/dbiqt02.pgn
wget http://www.chess88.net/pgn/spbw70.pgn
wget http://www.chess88.net/pgn/dubaigp02.pgn
wget http://www.chess88.net/pgn/eurotel02.pgn
wget http://www.chess88.net/pgn/smirin02.pgn
wget http://www.chess88.net/pgn/capae02.pgn
wget http://www.chess88.net/pgn/pojkovo3.pgn
wget http://www.chess88.net/pgn/gure02.pgn
wget http://www.chess88.net/pgn/borow02.pgn
wget http://www.chess88.net/pgn/sige02.pgn
wget http://www.chess88.net/pgn/sara02.pgn
wget http://www.chess88.net/pgn/eiwch02.pgn
wget http://www.chess88.net/pgn/rusteam.pgn
wget http://www.chess88.net/pgn/hunch02.pgn
wget http://www.chess88.net/pgn/Ruschwom.pgn
wget http://www.chess88.net/pgn/3iecc.pgn
wget http://www.chess88.net/pgn/moscgp02.pgn
wget http://www.chess88.net/pgn/chned02.pgn
wget http://www.chess88.net/pgn/manises02.pgn
wget http://www.chess88.net/pgn/wn02.pgn
wget http://www.chess88.net/pgn/chnedw02.pgn
wget http://www.chess88.net/pgn/dort02.pgn
wget http://www.chess88.net/pgn/gpsenat02.pgn
wget http://www.chess88.net/pgn/northsea02.pgn
wget http://www.chess88.net/pgn/chswe02.pgn
wget http://www.chess88.net/pgn/belfort02.pgn
wget http://www.chess88.net/pgn/chsvk02.pgn
wget http://www.chess88.net/pgn/swym02.pgn
wget http://www.chess88.net/pgn/biel02.pgn
wget http://www.chess88.net/pgn/lostboy02.pgn
wget http://www.chess88.net/pgn/wismil02.pgn
wget http://www.chess88.net/pgn/samara02.pgn
wget http://www.chess88.net/pgn/queens02.pgn
wget http://www.chess88.net/pgn/shredder02.pgn
wget http://www.chess88.net/pgn/chgbr02.pgn
wget http://www.chess88.net/pgn/babe02.pgn
wget http://www.chess88.net/pgn/polit02.pgn
wget http://www.chess88.net/pgn/mainzcc02.pgn
wget http://www.chess88.net/pgn/mainw02.pgn
wget http://www.chess88.net/pgn/chisl02.pgn
wget http://www.chess88.net/pgn/ordix02.pgn
wget http://www.chess88.net/pgn/wyco02.pgn
wget http://www.chess88.net/pgn/mvmcup02.pgn
wget http://www.chess88.net/pgn/botmen02.pgn
wget http://www.chess88.net/pgn/wdr02.pgn
wget http://www.chess88.net/pgn/chrus02.pgn
wget http://www.chess88.net/pgn/frach02.pgn
wget http://www.chess88.net/pgn/Sants02.pgn
wget http://www.chess88.net/pgn/rusrow02.pgn
wget http://www.chess88.net/pgn/chesp02.pgn
wget http://www.chess88.net/pgn/ecc02.pgn
wget http://www.chess88.net/pgn/chper02.pgn
wget http://www.chess88.net/pgn/monarch.pgn
wget http://www.chess88.net/pgn/rudenko02.pgn
wget http://www.chess88.net/pgn/albert02.pgn
wget http://www.chess88.net/pgn/essent02.pgn
wget http://www.chess88.net/pgn/milk02.pgn
wget http://www.chess88.net/pgn/essentopen02.pgn
wget http://www.chess88.net/pgn/wcc02.pgn
wget http://www.chess88.net/pgn/brains02.pgn
wget http://www.chess88.net/pgn/ol02_r.pgn
wget http://www.chess88.net/pgn/klak02.pgn
wget http://www.chess88.net/pgn/ol02_c.pgn
wget http://www.chess88.net/pgn/MosSpb02.pgn
wget http://www.chess88.net/pgn/corse02.pgn
wget http://www.chess88.net/pgn/capgp02.pgn
wget http://www.chess88.net/pgn/chwy02.pgn
wget http://www.chess88.net/pgn/chisr02.pgn
wget http://www.chess88.net/pgn/cura02.pgn
wget http://www.chess88.net/pgn/opatija.pgn
wget http://www.chess88.net/pgn/kasppaehtz.pgn
wget http://www.chess88.net/pgn/chita02.pgn
wget http://www.chess88.net/pgn/catisl.pgn
wget http://www.chess88.net/pgn/bali02.pgn
wget http://www.chess88.net/pgn/chger02.pgn
wget http://www.chess88.net/pgn/hscht02.pgn
wget http://www.chess88.net/pgn/chgre02.pgn
wget http://www.chess88.net/pgn/harm02.pgn
wget http://www.chess88.net/pgn/wjcc02.pgn
wget http://www.chess88.net/pgn/prem0203.pgn
wget http://www.chess88.net/pgn/torre02.pgn
wget http://www.chess88.net/pgn/naop02.pgn
wget http://www.chess88.net/pgn/x3dworld.pgn
wget http://www.chess88.net/pgn/rilt0203.pgn
wget http://www.chess88.net/pgn/pamp02.pgn
wget http://www.chess88.net/pgn/reggio0203.pgn
wget http://www.chess88.net/pgn/fidech2k.pgn
wget http://www.chess88.net/pgn/wijkb03.pgn
wget http://www.chess88.net/pgn/chusa03.pgn
wget http://www.chess88.net/pgn/keres03.pgn
wget http://www.chess88.net/pgn/chusa03wp.pgn
wget http://www.chess88.net/pgn/chind03.pgn
wget http://www.chess88.net/pgn/korsad03.pgn
wget http://www.chess88.net/pgn/kaspjun03.pgn
wget http://www.chess88.net/pgn/wijka03.pgn
wget http://www.chess88.net/pgn/lin03.pgn
wget http://www.chess88.net/pgn/dhaka03.pgn
wget http://www.chess88.net/pgn/lin99.pgn
wget http://www.chess88.net/pgn/amber03.pgn
wget http://www.chess88.net/pgn/cap03.pgn
wget http://www.chess88.net/pgn/Andbli03.pgn
wget http://www.chess88.net/pgn/anibal03.pgn
wget http://www.chess88.net/pgn/dosh03.pgn
wget http://www.chess88.net/pgn/edda03.pgn
wget http://www.chess88.net/pgn/chban03.pgn
wget http://www.chess88.net/pgn/sismh03.pgn
wget http://www.chess88.net/pgn/asiteam03.pgn
wget http://www.chess88.net/pgn/mackar03.pgn
wget http://www.chess88.net/pgn/buda03.pgn
wget http://www.chess88.net/pgn/chden03.pgn
wget http://www.chess88.net/pgn/chsco03.pgn
wget http://www.chess88.net/pgn/poik03.pgn
wget http://www.chess88.net/pgn/chmosc03.pgn
wget http://www.chess88.net/pgn/chstp03.pgn
wget http://www.chess88.net/pgn/chstpw03.pgn
wget http://www.chess88.net/pgn/swym03.pgn
wget http://www.chess88.net/pgn/polgel03.pgn
wget http://www.chess88.net/pgn/biel03.pgn
wget http://www.chess88.net/pgn/polit03.pgn
wget http://www.chess88.net/pgn/chgbr03.pgn
wget http://www.chess88.net/pgn/malmo03.pgn
wget http://www.chess88.net/pgn/zt33.pgn
wget http://www.chess88.net/pgn/dort03.pgn
wget http://www.chess88.net/pgn/mainz03.pgn
wget http://www.chess88.net/pgn/wchasia03.pgn
wget http://www.chess88.net/pgn/simp03.pgn
wget http://www.chess88.net/pgn/chrus03.pgn
wget http://www.chess88.net/pgn/kvqchn03.pgn
wget http://www.chess88.net/pgn/3arrow03.pgn
wget http://www.chess88.net/pgn/ym03.pgn
wget http://www.chess88.net/pgn/kingschn03.pgn
wget http://www.chess88.net/pgn/kasazm03.pgn
wget http://www.chess88.net/pgn/ecc03.pgn
wget http://www.chess88.net/pgn/arctic03.pgn
wget http://www.chess88.net/pgn/eccw03.pgn
wget http://www.chess88.net/pgn/samba03.pgn
wget http://www.chess88.net/pgn/eutch03.pgn
wget http://www.chess88.net/pgn/essent03.pgn
wget http://www.chess88.net/pgn/eutchw03.pgn
wget http://www.chess88.net/pgn/capgp03.pgn
wget http://www.chess88.net/pgn/capko03.pgn
wget http://www.chess88.net/pgn/milk03.pgn
wget http://www.chess88.net/pgn/bastiako03.pgn
wget http://www.chess88.net/pgn/x3dkf03.pgn
wget http://www.chess88.net/pgn/larola03.pgn
wget http://www.chess88.net/pgn/kornav03.pgn
wget http://www.chess88.net/pgn/wccc03.pgn
wget http://www.chess88.net/pgn/bali03.pgn
wget http://www.chess88.net/pgn/chind03a.pgn
wget http://www.chess88.net/pgn/decam03.pgn
wget http://www.chess88.net/pgn/belfort03.pgn
wget http://www.chess88.net/pgn/3naogm03.pgn
wget http://www.chess88.net/pgn/torre03.pgn
wget http://www.chess88.net/pgn/linds03.pgn
wget http://www.chess88.net/pgn/torreko03.pgn
wget http://www.chess88.net/pgn/pamp03.pgn
wget http://www.chess88.net/pgn/harm03.pgn
wget http://www.chess88.net/pgn/bcmast03.pgn
wget http://www.chess88.net/pgn/46reggio.pgn
wget http://www.chess88.net/pgn/prem0304.pgn
wget http://www.chess88.net/pgn/rilton03.pgn
wget http://www.chess88.net/pgn/wijka04.pgn
wget http://www.chess88.net/pgn/wijkb04.pgn
wget http://www.chess88.net/pgn/wijkc04.pgn
wget http://www.chess88.net/pgn/berm04.pgn
wget http://www.chess88.net/pgn/common04.pgn
wget http://www.chess88.net/pgn/kramsim04.pgn
wget http://www.chess88.net/pgn/anatop04.pgn
wget http://www.chess88.net/pgn/chger04.pgn
wget http://www.chess88.net/pgn/gibral04.pgn
wget http://www.chess88.net/pgn/frachn04.pgn
wget http://www.chess88.net/pgn/stebar04.pgn
wget http://www.chess88.net/pgn/breizh04.pgn
wget http://www.chess88.net/pgn/jakart04.pgn
wget http://www.chess88.net/pgn/lin04.pgn
wget http://www.chess88.net/pgn/ieccp04.pgn
wget http://www.chess88.net/pgn/poik04.pgn
wget http://www.chess88.net/pgn/reykrap04.pgn
wget http://www.chess88.net/pgn/tcas04.pgn
wget http://www.chess88.net/pgn/entel04.pgn
wget http://www.chess88.net/pgn/pina04.pgn
wget http://www.chess88.net/pgn/chban04.pgn
wget http://www.chess88.net/pgn/chstp04.pgn
wget http://www.chess88.net/pgn/cogas04.pgn
wget http://www.chess88.net/pgn/chden04.pgn
wget http://www.chess88.net/pgn/beer04.pgn
wget http://www.chess88.net/pgn/tchrus04.pgn
wget http://www.chess88.net/pgn/chpol04.pgn
wget http://www.chess88.net/pgn/chbul04.pgn
wget http://www.chess88.net/pgn/bacsok04.pgn
wget http://www.chess88.net/pgn/sige04.pgn
wget http://www.chess88.net/pgn/tchfra04.pgn
wget http://www.chess88.net/pgn/capae04.pgn
wget http://www.chess88.net/pgn/iecc04.pgn
wget http://www.chess88.net/pgn/sara04.pgn
wget http://www.chess88.net/pgn/wchwom04.pgn
wget http://www.chess88.net/pgn/chrussp04.pgn
wget http://www.chess88.net/pgn/chrusto04.pgn
wget http://www.chess88.net/pgn/wchwomf04.pgn
wget http://www.chess88.net/pgn/leonko04.pgn
wget http://www.chess88.net/pgn/paks04.pgn
wget http://www.chess88.net/pgn/armrow04.pgn
wget http://www.chess88.net/pgn/fideko04.pgn
wget http://www.chess88.net/pgn/chned04.pgn
wget http://www.chess88.net/pgn/vera04.pgn
wget http://www.chess88.net/pgn/taiyuan04.pgn
wget http://www.chess88.net/pgn/biel04.pgn
wget http://www.chess88.net/pgn/dort04.pgn
wget http://www.chess88.net/pgn/dortsf04.pgn
wget http://www.chess88.net/pgn/dortfi04.pgn
wget http://www.chess88.net/pgn/mainz04.pgn
wget http://www.chess88.net/pgn/ordixop04.pgn
wget http://www.chess88.net/pgn/sprap04.pgn
wget http://www.chess88.net/pgn/chukr04.pgn
wget http://www.chess88.net/pgn/pune04.pgn
wget http://www.chess88.net/pgn/ym04.pgn
wget http://www.chess88.net/pgn/chisr04.pgn
wget http://www.chess88.net/pgn/kramlek04.pgn
wget http://www.chess88.net/pgn/ecc04.pgn
wget http://www.chess88.net/pgn/ol04.pgn
wget http://www.chess88.net/pgn/eccw04.pgn
wget http://www.chess88.net/pgn/olm04.pgn
wget http://www.chess88.net/pgn/olw04.pgn
wget http://www.chess88.net/pgn/essent04.pgn
wget http://www.chess88.net/pgn/corsko04.pgn
wget http://www.chess88.net/pgn/chrus04.pgn
wget http://www.chess88.net/pgn/chusa04.pgn
wget http://www.chess88.net/pgn/wjun04.pgn
wget http://www.chess88.net/pgn/wjun04w.pgn
wget http://www.chess88.net/pgn/ashdod04.pgn
wget http://www.chess88.net/pgn/aixgp04.pgn
wget http://www.chess88.net/pgn/nakkar04.pgn
wget http://www.chess88.net/pgn/petmemint04.pgn
wget http://www.chess88.net/pgn/dramm0405.pgn
wget http://www.chess88.net/pgn/regg0405.pgn
wget http://www.chess88.net/pgn/harm04.pgn
wget http://www.chess88.net/pgn/wijka05.pgn
wget http://www.chess88.net/pgn/wijkb05.pgn
wget http://www.chess88.net/pgn/wijkc05.pgn
wget http://www.chess88.net/pgn/gibarl05.pgn
wget http://www.chess88.net/pgn/berm05.pgn
wget http://www.chess88.net/pgn/chcze05.pgn
wget http://www.chess88.net/pgn/aeroop05.pgn
wget http://www.chess88.net/pgn/capop05.pgn
wget http://www.chess88.net/pgn/lin05.pgn
wget http://www.chess88.net/pgn/poik05.pgn
wget http://www.chess88.net/pgn/chban05.pgn
wget http://www.chess88.net/pgn/anibal05.pgn
wget http://www.chess88.net/pgn/amber05.pgn
wget http://www.chess88.net/pgn/karist05.pgn
wget http://www.chess88.net/pgn/entel05.pgn
wget http://www.chess88.net/pgn/chstp05.pgn
wget http://www.chess88.net/pgn/chden05.pgn
wget http://www.chess88.net/pgn/dosherm05.pgn
wget http://www.chess88.net/pgn/cheu05.pgn
wget http://www.chess88.net/pgn/dubai05.pgn
wget http://www.chess88.net/pgn/dhaka05.pgn
wget http://www.chess88.net/pgn/top16a05.pgn
wget http://www.chess88.net/pgn/top16b05.pgn
wget http://www.chess88.net/pgn/chcuba05.pgn
wget http://www.chess88.net/pgn/chcubb05.pgn
wget http://www.chess88.net/pgn/gausgma05.pgn
wget http://www.chess88.net/pgn/gausgmb05.pgn
wget http://www.chess88.net/pgn/sige05.pgn
wget http://www.chess88.net/pgn/chcubko05.pgn
wget http://www.chess88.net/pgn/chpol05.pgn
wget http://www.chess88.net/pgn/tchrus05.pgn
wget http://www.chess88.net/pgn/charm05.pgn
wget http://www.chess88.net/pgn/gpbord05.pgn
wget http://www.chess88.net/pgn/capae05.pgn
wget http://www.chess88.net/pgn/capagr05.pgn
wget http://www.chess88.net/pgn/mtel05.pgn
wget http://www.chess88.net/pgn/chhun05.pgn
wget http://www.chess88.net/pgn/ys05.pgn
wget http://www.chess88.net/pgn/chhunw05.pgn
wget http://www.chess88.net/pgn/chrusw05.pgn
wget http://www.chess88.net/pgn/bosnia05.pgn
wget http://www.chess88.net/pgn/hbcc05.pgn
wget http://www.chess88.net/pgn/adalek05.pgn
wget http://www.chess88.net/pgn/frasc05.pgn
wget http://www.chess88.net/pgn/chbul05.pgn
wget http://www.chess88.net/pgn/leon05.pgn
wget http://www.chess88.net/pgn/timbru05.pgn
wget http://www.chess88.net/pgn/paks05.pgn
wget http://www.chess88.net/pgn/cheuro05.pgn
wget http://www.chess88.net/pgn/cheurw05.pgn
wget http://www.chess88.net/pgn/adahyd05.pgn
wget http://www.chess88.net/pgn/geller05.pgn
wget http://www.chess88.net/pgn/nurals05.pgn
wget http://www.chess88.net/pgn/chnfra05.pgn
wget http://www.chess88.net/pgn/dort05.pgn
wget http://www.chess88.net/pgn/sanjin05.pgn
wget http://www.chess88.net/pgn/vidmem05.pgn
wget http://www.chess88.net/pgn/canop05.pgn
wget http://www.chess88.net/pgn/merco05.pgn
wget http://www.chess88.net/pgn/biel05.pgn
wget http://www.chess88.net/pgn/sala05.pgn
wget http://www.chess88.net/pgn/act05.pgn
wget http://www.chess88.net/pgn/maccsu05.pgn
wget http://www.chess88.net/pgn/etc05.pgn
wget http://www.chess88.net/pgn/chgbr05.pgn
wget http://www.chess88.net/pgn/etcw05.pgn
wget http://www.chess88.net/pgn/mainzu05.pgn
wget http://www.chess88.net/pgn/mainzm05.pgn
wget http://www.chess88.net/pgn/amercon05.pgn
wget http://www.chess88.net/pgn/chfra05.pgn
wget http://www.chess88.net/pgn/staunt05.pgn
wget http://www.chess88.net/pgn/chfraw05.pgn
wget http://www.chess88.net/pgn/igu05.pgn
wget http://www.chess88.net/pgn/chrussf05.pgn
wget http://www.chess88.net/pgn/chned05.pgn
wget http://www.chess88.net/pgn/chnedw05.pgn
wget http://www.chess88.net/pgn/chukr05.pgn
wget http://www.chess88.net/pgn/lausym05.pgn
wget http://www.chess88.net/pgn/ecc05.pgn
wget http://www.chess88.net/pgn/eccw05.pgn
wget http://www.chess88.net/pgn/wchfide05.pgn
wget http://www.chess88.net/pgn/karabb05.pgn
wget http://www.chess88.net/pgn/samba05.pgn
wget http://www.chess88.net/pgn/essent05.pgn
wget http://www.chess88.net/pgn/barce05.pgn
wget http://www.chess88.net/pgn/wtc05.pgn
wget http://www.chess88.net/pgn/chnorp05.pgn
wget http://www.chess88.net/pgn/chnorpr05.pgn
wget http://www.chess88.net/pgn/corse05.pgn
wget http://www.chess88.net/pgn/mamed05.pgn
wget http://www.chess88.net/pgn/wjun05.pgn
wget http://www.chess88.net/pgn/wjung05.pgn
wget http://www.chess88.net/pgn/bilbao05.pgn
wget http://www.chess88.net/pgn/wcup05.pgn
wget http://www.chess88.net/pgn/chrus05.pgn
wget http://www.chess88.net/pgn/torreko05.pgn
wget http://www.chess88.net/pgn/pamp05.pgn
wget http://www.chess88.net/pgn/harm05.pgn
wget http://www.chess88.net/pgn/hast05.pgn
wget http://www.chess88.net/pgn/reggio05.pgn
wget http://www.chess88.net/pgn/keres06.pgn
wget http://www.chess88.net/pgn/relt05.pgn
wget http://www.chess88.net/pgn/keresw06.pgn
wget http://www.chess88.net/pgn/wijka06.pgn
wget http://www.chess88.net/pgn/wijkb06.pgn
wget http://www.chess88.net/pgn/wijkc06.pgn
wget http://www.chess88.net/pgn/gibr06.pgn
wget http://www.chess88.net/pgn/chgeo06.pgn
wget http://www.chess88.net/pgn/moscop06.pgn
wget http://www.chess88.net/pgn/cuerym06.pgn
wget http://www.chess88.net/pgn/fiber06.pgn
wget http://www.chess88.net/pgn/aero06.pgn
wget http://www.chess88.net/pgn/chger06.pgn
wget http://www.chess88.net/pgn/chcze06.pgn
wget http://www.chess88.net/pgn/morlin06.pgn
wget http://www.chess88.net/pgn/cap06.pgn
wget http://www.chess88.net/pgn/chpol06.pgn
wget http://www.chess88.net/pgn/pulver06.pgn
wget http://www.chess88.net/pgn/chhun06.pgn
wget http://www.chess88.net/pgn/chusaa06.pgn
wget http://www.chess88.net/pgn/u20chrus06.pgn
wget http://www.chess88.net/pgn/chusab06.pgn
wget http://www.chess88.net/pgn/u20chrusw06.pgn
wget http://www.chess88.net/pgn/reykop06.pgn
wget http://www.chess88.net/pgn/wchwom06.pgn
wget http://www.chess88.net/pgn/chban06.pgn
wget http://www.chess88.net/pgn/chusaf06.pgn
wget http://www.chess88.net/pgn/chusawf06.pgn
wget http://www.chess88.net/pgn/chtur06.pgn
wget http://www.chess88.net/pgn/poik06.pgn
wget http://www.chess88.net/pgn/charm06.pgn
wget http://www.chess88.net/pgn/laroche06.pgn
wget http://www.chess88.net/pgn/chind06.pgn
wget http://www.chess88.net/pgn/topnis06.pgn
wget http://www.chess88.net/pgn/cheuro06.pgn
wget http://www.chess88.net/pgn/cheurow06.pgn
wget http://www.chess88.net/pgn/chden06.pgn
wget http://www.chess88.net/pgn/chdeng06.pgn
wget http://www.chess88.net/pgn/cogas06.pgn
wget http://www.chess88.net/pgn/dubai06.pgn
wget http://www.chess88.net/pgn/welcar06.pgn
wget http://www.chess88.net/pgn/tchrus06.pgn
wget http://www.chess88.net/pgn/tchrus106.pgn
wget http://www.chess88.net/pgn/tchrusw06.pgn
wget http://www.chess88.net/pgn/sige06.pgn
wget http://www.chess88.net/pgn/tchfrat1606.pgn
wget http://www.chess88.net/pgn/bosnia06.pgn
wget http://www.chess88.net/pgn/bosniab06.pgn
wget http://www.chess88.net/pgn/mtel06.pgn
wget http://www.chess88.net/pgn/ystars06.pgn
wget http://www.chess88.net/pgn/olup06.pgn
wget http://www.chess88.net/pgn/tchnedp06.pgn
wget http://www.chess88.net/pgn/ol06.pgn
wget http://www.chess88.net/pgn/olw06.pgn
wget http://www.chess88.net/pgn/karspa06.pgn
wget http://www.chess88.net/pgn/hock06.pgn
wget http://www.chess88.net/pgn/leon06.pgn
wget http://www.chess88.net/pgn/foros06.pgn
wget http://www.chess88.net/pgn/chned06.pgn
wget http://www.chess88.net/pgn/midnight06.pgn
wget http://www.chess88.net/pgn/worldop06.pgn
wget http://www.chess88.net/pgn/taiyuan06.pgn
wget http://www.chess88.net/pgn/chnor06.pgn
wget http://www.chess88.net/pgn/swls06.pgn
wget http://www.chess88.net/pgn/izmailov06.pgn
wget http://www.chess88.net/pgn/womcup06.pgn
wget http://www.chess88.net/pgn/act06.pgn
wget http://www.chess88.net/pgn/canop06.pgn
wget http://www.chess88.net/pgn/chsco06.pgn
wget http://www.chess88.net/pgn/bielgm06.pgn
wget http://www.chess88.net/pgn/nuralcup06.pgn
wget http://www.chess88.net/pgn/bielwom06.pgn
wget http://www.chess88.net/pgn/paks06.pgn
wget http://www.chess88.net/pgn/dort06.pgn
wget http://www.chess88.net/pgn/liepaja06.pgn
wget http://www.chess88.net/pgn/chgbr06.pgn
wget http://www.chess88.net/pgn/staunt06.pgn
wget http://www.chess88.net/pgn/chfra06.pgn
wget http://www.chess88.net/pgn/mainzm06.pgn
wget http://www.chess88.net/pgn/chfraw06.pgn
wget http://www.chess88.net/pgn/monta06.pgn
wget http://www.chess88.net/pgn/montb06.pgn
wget http://www.chess88.net/pgn/gelnav06.pgn
wget http://www.chess88.net/pgn/horjac06.pgn
wget http://www.chess88.net/pgn/acropw06.pgn
wget http://www.chess88.net/pgn/acrop06.pgn
wget http://www.chess88.net/pgn/nhhotels06.pgn
wget http://www.chess88.net/pgn/chnrus06.pgn
wget http://www.chess88.net/pgn/abud06.pgn
wget http://www.chess88.net/pgn/chnrusw06.pgn
wget http://www.chess88.net/pgn/licht06.pgn
wget http://www.chess88.net/pgn/rubmem06.pgn
wget http://www.chess88.net/pgn/lekkar06.pgn
wget http://www.chess88.net/pgn/hereford06.pgn
wget http://www.chess88.net/pgn/carsvi06.pgn
wget http://www.chess88.net/pgn/chesscr06.pgn
wget http://www.chess88.net/pgn/agdfir06.pgn
wget http://www.chess88.net/pgn/frachn06.pgn
wget http://www.chess88.net/pgn/wblitz06.pgn
wget http://www.chess88.net/pgn/frachnw06.pgn
wget http://www.chess88.net/pgn/wblitzp06.pgn
wget http://www.chess88.net/pgn/chrusq06.pgn
wget http://www.chess88.net/pgn/cheu06.pgn
wget http://www.chess88.net/pgn/agdcar06.pgn
wget http://www.chess88.net/pgn/kratop06.pgn
wget http://www.chess88.net/pgn/tchespg06.pgn
wget http://www.chess88.net/pgn/kratopp06.pgn
wget http://www.chess88.net/pgn/ecc06.pgn
wget http://www.chess88.net/pgn/wjun06.pgn
wget http://www.chess88.net/pgn/eccw06.pgn
wget http://www.chess88.net/pgn/wjung06.pgn
wget http://www.chess88.net/pgn/barc06.pgn
wget http://www.chess88.net/pgn/essent06.pgn
wget http://www.chess88.net/pgn/essentop06.pgn
wget http://www.chess88.net/pgn/capa06.pgn
wget http://www.chess88.net/pgn/capb06.pgn
wget http://www.chess88.net/pgn/capbt06.pgn
wget http://www.chess88.net/pgn/capko06.pgn
wget http://www.chess88.net/pgn/tchesp06.pgn
wget http://www.chess88.net/pgn/talmem06.pgn
wget http://www.chess88.net/pgn/corsmast06.pgn
wget http://www.chess88.net/pgn/krafri06.pgn
wget http://www.chess88.net/pgn/capmem06.pgn
wget http://www.chess88.net/pgn/chespa06.pgn
wget http://www.chess88.net/pgn/remco06.pgn
wget http://www.chess88.net/pgn/chespb06.pgn
wget http://www.chess88.net/pgn/chespko06.pgn
wget http://www.chess88.net/pgn/chespsch06.pgn
wget http://www.chess88.net/pgn/chrus06.pgn
wget http://www.chess88.net/pgn/chgre06.pgn
wget http://www.chess88.net/pgn/junrad06.pgn
wget http://www.chess88.net/pgn/chgrew06.pgn
wget http://www.chess88.net/pgn/toppol06.pgn
wget http://www.chess88.net/pgn/chrusp06.pgn
wget http://www.chess88.net/pgn/torreko06.pgn
wget http://www.chess88.net/pgn/torre06.pgn
wget http://www.chess88.net/pgn/neglah06.pgn
wget http://www.chess88.net/pgn/pamp06.pgn
wget http://www.chess88.net/pgn/hast06.pgn
wget http://www.chess88.net/pgn/astana06.pgn
wget http://www.chess88.net/pgn/acprap07.pgn
wget http://www.chess88.net/pgn/reggio06.pgn
wget http://www.chess88.net/pgn/wijka07.pgn
wget http://www.chess88.net/pgn/wijkb07.pgn
wget http://www.chess88.net/pgn/wijkc07.pgn
wget http://www.chess88.net/pgn/gibtel07.pgn
wget http://www.chess88.net/pgn/moscop07.pgn
wget http://www.chess88.net/pgn/morlin07.pgn
wget http://www.chess88.net/pgn/aero07.pgn
wget http://www.chess88.net/pgn/chpol07.pgn
wget http://www.chess88.net/pgn/morelia07.pgn
wget http://www.chess88.net/pgn/capop07.pgn
wget http://www.chess88.net/pgn/poik07.pgn
wget http://www.chess88.net/pgn/amberr07.pgn
wget http://www.chess88.net/pgn/ruylop07.pgn
wget http://www.chess88.net/pgn/amberb07.pgn
wget http://www.chess88.net/pgn/cheuro07.pgn
wget http://www.chess88.net/pgn/canrap07.pgn
wget http://www.chess88.net/pgn/cheurow07.pgn
wget http://www.chess88.net/pgn/chban07.pgn
wget http://www.chess88.net/pgn/porspa07.pgn
wget http://www.chess88.net/pgn/chden07.pgn
wget http://www.chess88.net/pgn/arokra07.pgn
wget http://www.chess88.net/pgn/lekkra07.pgn
wget http://www.chess88.net/pgn/sige07.pgn
wget http://www.chess88.net/pgn/gausgm07.pgn
wget http://www.chess88.net/pgn/tchrus07.pgn
wget http://www.chess88.net/pgn/chmos07.pgn
wget http://www.chess88.net/pgn/baku07.pgn
wget http://www.chess88.net/pgn/mtel07.pgn
wget http://www.chess88.net/pgn/chusa07.pgn
wget http://www.chess88.net/pgn/brutop07.pgn
wget http://www.chess88.net/pgn/capmeme07.pgn
wget http://www.chess88.net/pgn/sara07.pgn
wget http://www.chess88.net/pgn/wwtcc07.pgn
wget http://www.chess88.net/pgn/sarab07.pgn
wget http://www.chess88.net/pgn/radcar07.pgn
wget http://www.chess88.net/pgn/wyouth07.pgn
wget http://www.chess88.net/pgn/wchcansf07.pgn
wget http://www.chess88.net/pgn/nesis07.pgn
wget http://www.chess88.net/pgn/wchcanf07.pgn
wget http://www.chess88.net/pgn/capmema07.pgn
wget http://www.chess88.net/pgn/frijun07.pgn
wget http://www.chess88.net/pgn/valj07.pgn
wget http://www.chess88.net/pgn/foros07.pgn
wget http://www.chess88.net/pgn/chned07.pgn
wget http://www.chess88.net/pgn/bazna07.pgn
wget http://www.chess88.net/pgn/chnedw07.pgn
wget http://www.chess88.net/pgn/dort07.pgn
wget http://www.chess88.net/pgn/chnedp07.pgn
wget http://www.chess88.net/pgn/pivd07.pgn
wget http://www.chess88.net/pgn/worldop07.pgn
wget http://www.chess88.net/pgn/taiyuna07.pgn
wget http://www.chess88.net/pgn/leon07.pgn
wget http://www.chess88.net/pgn/canop07.pgn
wget http://www.chess88.net/pgn/chusaw07.pgn
wget http://www.chess88.net/pgn/nural07.pgn
wget http://www.chess88.net/pgn/montw07.pgn
wget http://www.chess88.net/pgn/banja07.pgn
wget http://www.chess88.net/pgn/mont07.pgn
wget http://www.chess88.net/pgn/biel07.pgn
wget http://www.chess88.net/pgn/chgbr07.pgn
wget http://www.chess88.net/pgn/bielp07.pgn
wget http://www.chess88.net/pgn/euwest07.pgn
wget http://www.chess88.net/pgn/mainzrp07.pgn
wget http://www.chess88.net/pgn/mainzrf07.pgn
wget http://www.chess88.net/pgn/mainzrtf07.pgn
wget http://www.chess88.net/pgn/mainzord07.pgn
wget http://www.chess88.net/pgn/cezns07.pgn
wget http://www.chess88.net/pgn/nh07.pgn
wget http://www.chess88.net/pgn/ceztj07.pgn
wget http://www.chess88.net/pgn/ruschn07.pgn
wget http://www.chess88.net/pgn/ukchn07.pgn
wget http://www.chess88.net/pgn/chrushl07.pgn
wget http://www.chess88.net/pgn/coal07.pgn
wget http://www.chess88.net/pgn/wchmex07.pgn
wget http://www.chess88.net/pgn/ecc07.pgn
wget http://www.chess88.net/pgn/wjun07.pgn
wget http://www.chess88.net/pgn/eccw07.pgn
wget http://www.chess88.net/pgn/wjung07.pgn
wget http://www.chess88.net/pgn/essent07.pgn
wget http://www.chess88.net/pgn/blindfwc07.pgn
wget http://www.chess88.net/pgn/essentop07.pgn
wget http://www.chess88.net/pgn/calviaop07.pgn
wget http://www.chess88.net/pgn/barca07.pgn
wget http://www.chess88.net/pgn/tchespf07.pgn
wget http://www.chess88.net/pgn/cors07.pgn
wget http://www.chess88.net/pgn/ivalekr07.pgn
wget http://www.chess88.net/pgn/vitoria07.pgn
wget http://www.chess88.net/pgn/etcc07.pgn
wget http://www.chess88.net/pgn/etccw07.pgn
wget http://www.chess88.net/pgn/talmem07.pgn
wget http://www.chess88.net/pgn/ussryug07.pgn
wget http://www.chess88.net/pgn/wblitz07.pgn
wget http://www.chess88.net/pgn/wcup07.pgn
wget http://www.chess88.net/pgn/chrus07.pgn
wget http://www.chess88.net/pgn/chrusw07.pgn
wget http://www.chess88.net/pgn/pamp07.pgn
wget http://www.chess88.net/pgn/harma07.pgn
wget http://www.chess88.net/pgn/torre07.pgn
wget http://www.chess88.net/pgn/torrew07.pgn
wget http://www.chess88.net/pgn/reggio0708.pgn
wget http://www.chess88.net/pgn/hast0708.pgn
wget http://www.chess88.net/pgn/acprap08.pgn
wget http://www.chess88.net/pgn/charm08.pgn
wget http://www.chess88.net/pgn/wijka08.pgn
wget http://www.chess88.net/pgn/wijkb08.pgn
wget http://www.chess88.net/pgn/wijkc08.pgn
wget http://www.chess88.net/pgn/maalot08.pgn
wget http://www.chess88.net/pgn/wijkh08.pgn
wget http://www.chess88.net/pgn/chcro08.pgn
wget http://www.chess88.net/pgn/gib08.pgn
wget http://www.chess88.net/pgn/moscop08.pgn
wget http://www.chess88.net/pgn/morlin08.pgn
wget http://www.chess88.net/pgn/noteboom08.pgn
wget http://www.chess88.net/pgn/aero08.pgn
wget http://www.chess88.net/pgn/pfalz08.pgn
wget http://www.chess88.net/pgn/capop08.pgn
wget http://www.chess88.net/pgn/amberb08.pgn
wget http://www.chess88.net/pgn/heviz08.pgn
wget http://www.chess88.net/pgn/amberr08.pgn
wget http://www.chess88.net/pgn/tchrus08.pgn
wget http://www.chess88.net/pgn/chned08.pgn
wget http://www.chess88.net/pgn/ruylop08.pgn
wget http://www.chess88.net/pgn/chnedw08.pgn
wget http://www.chess88.net/pgn/gausgma08.pgn
wget http://www.chess88.net/pgn/dubai08.pgn
wget http://www.chess88.net/pgn/sige08.pgn
wget http://www.chess88.net/pgn/dosherm08.pgn
wget http://www.chess88.net/pgn/plov08.pgn
wget http://www.chess88.net/pgn/plovw08.pgn
wget http://www.chess88.net/pgn/baku08.pgn
wget http://www.chess88.net/pgn/plovp08.pgn
wget http://www.chess88.net/pgn/mtel08.pgn
wget http://www.chess88.net/pgn/plovpw08.pgn
wget http://www.chess88.net/pgn/cez08.pgn
wget http://www.chess88.net/pgn/chusa08.pgn
wget http://www.chess88.net/pgn/chmos08.pgn
wget http://www.chess88.net/pgn/chusaw08.pgn
wget http://www.chess88.net/pgn/bakuop08.pgn
wget http://www.chess88.net/pgn/chusawp08.pgn
wget http://www.chess88.net/pgn/saraa08.pgn
wget http://www.chess88.net/pgn/charg08.pgn
wget http://www.chess88.net/pgn/sarab08.pgn
wget http://www.chess88.net/pgn/chargp08.pgn
wget http://www.chess88.net/pgn/lekcar08.pgn
wget http://www.chess88.net/pgn/pivd08.pgn
wget http://www.chess88.net/pgn/leon08.pgn
wget http://www.chess88.net/pgn/baz08.pgn
wget http://www.chess88.net/pgn/natop08.pgn
wget http://www.chess88.net/pgn/foros08.pgn
wget http://www.chess88.net/pgn/pearl08.pgn
wget http://www.chess88.net/pgn/karsho08.pgn
wget http://www.chess88.net/pgn/poik08.pgn
wget http://www.chess88.net/pgn/sevan08.pgn
wget http://www.chess88.net/pgn/biel08.pgn
wget http://www.chess88.net/pgn/paks08.pgn
wget http://www.chess88.net/pgn/bielp08.pgn
wget http://www.chess88.net/pgn/nural08.pgn
wget http://www.chess88.net/pgn/chgbr08.pgn
wget http://www.chess88.net/pgn/sochi08.pgn
wget http://www.chess88.net/pgn/mainz08.pgn
wget http://www.chess88.net/pgn/mainzor08.pgn
wget http://www.chess88.net/pgn/mainzf08.pgn
wget http://www.chess88.net/pgn/mainzt08.pgn
wget http://www.chess88.net/pgn/najmem08.pgn
wget http://www.chess88.net/pgn/vrob08.pgn
wget http://www.chess88.net/pgn/najop08.pgn
wget http://www.chess88.net/pgn/chgbrp08.pgn
wget http://www.chess88.net/pgn/staunt08.pgn
wget http://www.chess88.net/pgn/chfra08.pgn
wget http://www.chess88.net/pgn/wjun08.pgn
wget http://www.chess88.net/pgn/chfrab08.pgn
wget http://www.chess88.net/pgn/wjung08.pgn
wget http://www.chess88.net/pgn/chfraw08.pgn
wget http://www.chess88.net/pgn/talmem08.pgn
wget http://www.chess88.net/pgn/nh08.pgn
wget http://www.chess88.net/pgn/antgm08.pgn
wget http://www.chess88.net/pgn/mont08.pgn
wget http://www.chess88.net/pgn/talmembl08.pgn
wget http://www.chess88.net/pgn/wchw08.pgn
wget http://www.chess88.net/pgn/bilbao08.pgn
wget http://www.chess88.net/pgn/wchwf08.pgn
wget http://www.chess88.net/pgn/chrush08.pgn
wget http://www.chess88.net/pgn/tchesp108.pgn
wget http://www.chess88.net/pgn/cheu08.pgn
wget http://www.chess88.net/pgn/tchesp208.pgn
wget http://www.chess88.net/pgn/chnrus08.pgn
wget http://www.chess88.net/pgn/spice08.pgn
wget http://www.chess88.net/pgn/chrus08.pgn
wget http://www.chess88.net/pgn/wch08.pgn
wget http://www.chess88.net/pgn/chrusp08.pgn
wget http://www.chess88.net/pgn/capdag08.pgn
wget http://www.chess88.net/pgn/wblitz08.pgn
wget http://www.chess88.net/pgn/icccorus08.pgn
wget http://www.chess88.net/pgn/ol08.pgn
wget http://www.chess88.net/pgn/olw08.pgn
wget http://www.chess88.net/pgn/mianz09.pgn
wget http://www.chess88.net/pgn/mianzt09.pgn
wget http://www.chess88.net/pgn/mianzor09.pgn
wget http://www.chess88.net/pgn/mianzf09.pgn
wget http://www.chess88.net/pgn/ivalek09.pgn
wget http://www.chess88.net/pgn/akerp09.pgn
wget http://www.chess88.net/pgn/hast08.pgn
wget http://www.chess88.net/pgn/akerf09.pgn
wget http://www.chess88.net/pgn/corusa09.pgn
wget http://www.chess88.net/pgn/corusc09.pgn
wget http://www.chess88.net/pgn/gibtel09.pgn
wget http://www.chess88.net/pgn/bunrat09.pgn
wget http://www.chess88.net/pgn/aero09.pgn
wget http://www.chess88.net/pgn/topkam09.pgn
wget http://www.chess88.net/pgn/capp09.pgn
wget http://www.chess88.net/pgn/lin09.pgn
wget http://www.chess88.net/pgn/cheur09.pgn
wget http://www.chess88.net/pgn/istanw09.pgn
wget http://www.chess88.net/pgn/belgw09.pgn
wget http://www.chess88.net/pgn/cheurw09.pgn
wget http://www.chess88.net/pgn/vars09.pgn
wget http://www.chess88.net/pgn/amberb09.pgn
wget http://www.chess88.net/pgn/amberr09.pgn
wget http://www.chess88.net/pgn/cheurwt09.pgn
wget http://www.chess88.net/pgn/cheurp09.pgn
wget http://www.chess88.net/pgn/dort09.pgn
wget http://www.chess88.net/pgn/slick09.pgn
wget http://www.chess88.net/pgn/chban09.pgn
wget http://www.chess88.net/pgn/worldop09.pgn
wget http://www.chess88.net/pgn/dono09.pgn
wget http://www.chess88.net/pgn/chegy09.pgn
wget http://www.chess88.net/pgn/donop09.pgn
wget http://www.chess88.net/pgn/riordan09.pgn
wget http://www.chess88.net/pgn/canop09.pgn
wget http://www.chess88.net/pgn/sevan09.pgn
wget http://www.chess88.net/pgn/chsco09.pgn
wget http://www.chess88.net/pgn/riordanb09.pgn
wget http://www.chess88.net/pgn/biel09.pgn
wget http://www.chess88.net/pgn/polit09.pgn
wget http://www.chess88.net/pgn/najmem09.pgn
wget http://www.chess88.net/pgn/dutchop09.pgn
wget http://www.chess88.net/pgn/andop09.pgn
wget http://www.chess88.net/pgn/villarrob09.pgn
wget http://www.chess88.net/pgn/chgbr09.pgn
wget http://www.chess88.net/pgn/wch10.pgn
wget http://www.chess88.net/pgn/azewor10.pgn
wget http://www.chess88.net/pgn/nalwgp10.pgn
wget http://www.chess88.net/pgn/astrgp10.pgn
wget http://www.chess88.net/pgn/chcze10.pgn
wget http://www.chess88.net/pgn/bosna10.pgn
wget http://www.chess88.net/pgn/lublin10.pgn
wget http://www.chess88.net/pgn/chusa10.pgn
wget http://www.chess88.net/pgn/chchnw10.pgn
wget http://www.chess88.net/pgn/chusaq10.pgn
wget http://www.chess88.net/pgn/chchn10.pgn
wget http://www.chess88.net/pgn/chusap10.pgn
wget http://www.chess88.net/pgn/acprap10.pgn
wget http://www.chess88.net/pgn/sige10.pgn
wget http://www.chess88.net/pgn/poik10.pgn
wget http://www.chess88.net/pgn/leon10.pgn
wget http://www.chess88.net/pgn/tchchn10.pgn
wget http://www.chess88.net/pgn/danzgm10.pgn
wget http://www.chess88.net/pgn/ruylopmag10.pgn
wget http://www.chess88.net/pgn/medias10.pgn
wget http://www.chess88.net/pgn/pulaop10.pgn
wget http://www.chess88.net/pgn/balatgm110.pgn
wget http://www.chess88.net/pgn/jermukw10.pgn
wget http://www.chess88.net/pgn/balatgm210.pgn
wget http://www.chess88.net/pgn/capmeme10.pgn
wget http://www.chess88.net/pgn/capmemop10.pgn
wget http://www.chess88.net/pgn/capmemp10.pgn
wget http://www.chess88.net/pgn/wroclawop10.pgn
wget http://www.chess88.net/pgn/worldop10.pgn
wget http://www.chess88.net/pgn/hsgopa10.pgn
wget http://www.chess88.net/pgn/chusaw10.pgn
wget http://www.chess88.net/pgn/chusaj10.pgn
wget http://www.chess88.net/pgn/tchgre10.pgn
wget http://www.chess88.net/pgn/chsco10.pgn
wget http://www.chess88.net/pgn/dort10.pgn
wget http://www.chess88.net/pgn/lct10.pgn
wget http://www.chess88.net/pgn/najopa10.pgn
wget http://www.chess88.net/pgn/bielygm10.pgn
wget http://www.chess88.net/pgn/czechopgm10.pgn
wget http://www.chess88.net/pgn/chusaj10p.pgn
wget http://www.chess88.net/pgn/czechrap10.pgn
wget http://www.chess88.net/pgn/chgbr10.pgn
wget http://www.chess88.net/pgn/dutchop10.pgn
wget http://www.chess88.net/pgn/bielygmp10.pgn
wget http://www.chess88.net/pgn/ulaanwgp10.pgn
wget http://www.chess88.net/pgn/polit10.pgn
wget http://www.chess88.net/pgn/arctic10.pgn
wget http://www.chess88.net/pgn/wjun10.pgn
wget http://www.chess88.net/pgn/chnrus10.pgn
wget http://www.chess88.net/pgn/wjung10.pgn
wget http://www.chess88.net/pgn/chnrusw10.pgn
wget http://www.chess88.net/pgn/marxgm10.pgn
wget http://www.chess88.net/pgn/mainzr10.pgn
wget http://www.chess88.net/pgn/marxwgm10.pgn
wget http://www.chess88.net/pgn/hzop10.pgn
wget http://www.chess88.net/pgn/chfra10.pgn
wget http://www.chess88.net/pgn/chnrusr10.pgn
wget http://www.chess88.net/pgn/chfraw10.pgn
wget http://www.chess88.net/pgn/chnruswr10.pgn
wget http://www.chess88.net/pgn/chfrab10.pgn
wget http://www.chess88.net/pgn/efimnaid10.pgn
wget http://www.chess88.net/pgn/ectym10.pgn
wget http://www.chess88.net/pgn/nh10.pgn
wget http://www.chess88.net/pgn/abudma10.pgn
wget http://www.chess88.net/pgn/chfrap10.pgn
wget http://www.chess88.net/pgn/santsop10.pgn
wget http://www.chess88.net/pgn/nhp10.pgn
wget http://www.chess88.net/pgn/bdoprem10.pgn
wget http://www.chess88.net/pgn/tchesphon10.pgn
wget http://www.chess88.net/pgn/bdochall10.pgn
wget http://www.chess88.net/pgn/bakuop10.pgn
wget http://www.chess88.net/pgn/lekgel10.pgn
wget http://www.chess88.net/pgn/chrushl10.pgn
wget http://www.chess88.net/pgn/arcticstarsp10.pgn
wget http://www.chess88.net/pgn/arcticstarsf10.pgn
wget http://www.chess88.net/pgn/arcticstars310.pgn
wget http://www.chess88.net/pgn/shanghai10.pgn
wget http://www.chess88.net/pgn/chesp10.pgn
wget http://www.chess88.net/pgn/shanghaip10.pgn
wget http://www.chess88.net/pgn/tchcro1a10.pgn
wget http://www.chess88.net/pgn/wuccm10.pgn
wget http://www.chess88.net/pgn/tchcro1b10.pgn
wget http://www.chess88.net/pgn/wuccw10.pgn
wget http://www.chess88.net/pgn/tchcrow10.pgn
wget http://www.chess88.net/pgn/inventi10.pgn
wget http://www.chess88.net/pgn/olymm10.pgn
wget http://www.chess88.net/pgn/olymw10.pgn
wget http://www.chess88.net/pgn/bilbao10.pgn
wget http://www.chess88.net/pgn/bund1011.pgn
wget http://www.chess88.net/pgn/eccm10.pgn
wget http://www.chess88.net/pgn/eccw10.pgn
wget http://www.chess88.net/pgn/pearl10.pgn
wget http://www.chess88.net/pgn/captgpa10.pgn
wget http://www.chess88.net/pgn/unive10.pgn
wget http://www.chess88.net/pgn/captgpb10.pgn
wget http://www.chess88.net/pgn/spicegma10.pgn
wget http://www.chess88.net/pgn/spicegmb10.pgn
wget http://www.chess88.net/pgn/talmem10.pgn
wget http://www.chess88.net/pgn/captko10.pgn
wget http://www.chess88.net/pgn/wblitz10.pgn
wget http://www.chess88.net/pgn/chrusw10.pgn
wget http://www.chess88.net/pgn/asianmr10.pgn
wget http://www.chess88.net/pgn/asianmt10.pgn
wget http://www.chess88.net/pgn/asianwr10.pgn
wget http://www.chess88.net/pgn/asianwt10.pgn
wget http://www.chess88.net/pgn/chisr10.pgn
wget http://www.chess88.net/pgn/cultv10.pgn
wget http://www.chess88.net/pgn/asianmtf10.pgn
wget http://www.chess88.net/pgn/asianwtf10.pgn
wget http://www.chess88.net/pgn/chita10.pgn
wget http://www.chess88.net/pgn/remcogm10.pgn
wget http://www.chess88.net/pgn/chbra10.pgn
wget http://www.chess88.net/pgn/remcoop10.pgn
wget http://www.chess88.net/pgn/chgre10.pgn
wget http://www.chess88.net/pgn/karmilr10.pgn
wget http://www.chess88.net/pgn/wchw10.pgn
wget http://www.chess88.net/pgn/kilken10.pgn
wget http://www.chess88.net/pgn/chrus10.pgn
wget http://www.chess88.net/pgn/loncc10.pgn
wget http://www.chess88.net/pgn/lonccw10.pgn
wget http://www.chess88.net/pgn/lonccf10.pgn
wget http://www.chess88.net/pgn/amplicor10.pgn
wget http://www.chess88.net/pgn/lonccfb10.pgn
wget http://www.chess88.net/pgn/amplicob10.pgn
wget http://www.chess88.net/pgn/chrusp10.pgn
wget http://www.chess88.net/pgn/groninga10.pgn
wget http://www.chess88.net/pgn/hastm1011.pgn
wget http://www.chess88.net/pgn/regg1011.pgn
wget http://www.chess88.net/pgn/wijka11.pgn
wget http://www.chess88.net/pgn/wijkc11.pgn
wget http://www.chess88.net/pgn/wijkb11.pgn
wget http://www.chess88.net/pgn/gibral11.pgn
wget http://www.chess88.net/pgn/aeroa11.pgn
wget http://www.chess88.net/pgn/cento11.pgn
wget http://www.chess88.net/pgn/aerob11.pgn
wget http://www.chess88.net/pgn/dohawgp11.pgn
wget http://www.chess88.net/pgn/batavgr11.pgn
wget http://www.chess88.net/pgn/bunrat11.pgn
wget http://www.chess88.net/pgn/cappellop11.pgn
wget http://www.chess88.net/pgn/controc11.pgn
wget http://www.chess88.net/pgn/chsrb11.pgn
wget http://www.chess88.net/pgn/chrusu2011.pgn
wget http://www.chess88.net/pgn/chrusu20w11.pgn
wget http://www.chess88.net/pgn/reykop11.pgn
wget http://www.chess88.net/pgn/amberb11.pgn
wget http://www.chess88.net/pgn/stlouisinv11.pgn
wget http://www.chess88.net/pgn/amberr11.pgn
wget http://www.chess88.net/pgn/stlouisinvp11.pgn
wget http://www.chess88.net/pgn/cheur11.pgn
wget http://www.chess88.net/pgn/anakasrm11.pgn
wget http://www.chess88.net/pgn/chchn11.pgn
wget http://www.chess88.net/pgn/cheursen11.pgn
wget http://www.chess88.net/pgn/chchnw11.pgn
wget http://www.chess88.net/pgn/dubaiop11.pgn
wget http://www.chess88.net/pgn/thaiop11.pgn
wget http://www.chess88.net/pgn/tchrusp11.pgn
wget http://www.chess88.net/pgn/tchchn11.pgn
wget http://www.chess88.net/pgn/chusagpa11.pgn
wget http://www.chess88.net/pgn/chusagpb11.pgn
wget http://www.chess88.net/pgn/chusawp11.pgn
wget http://www.chess88.net/pgn/chisl11.pgn
wget http://www.chess88.net/pgn/chncelebw11.pgn
wget http://www.chess88.net/pgn/tchrusw11.pgn
wget http://www.chess88.net/pgn/lundgm11.pgn
wget http://www.chess88.net/pgn/chusagpbp11.pgn
wget http://www.chess88.net/pgn/chusawpp11.pgn
wget http://www.chess88.net/pgn/chusako11.pgn
wget http://www.chess88.net/pgn/chusawko11.pgn
wget http://www.chess88.net/pgn/tchrusr11.pgn
wget http://www.chess88.net/pgn/asiancit11.pgn
wget http://www.chess88.net/pgn/tchruswr11.pgn
wget http://www.chess88.net/pgn/nakhchop11.pgn
wget http://www.chess88.net/pgn/chasiaind11.pgn
wget http://www.chess88.net/pgn/bosna11.pgn
wget http://www.chess88.net/pgn/wchcand11.pgn
wget http://www.chess88.net/pgn/chasiaindw11.pgn
wget http://www.chess88.net/pgn/capmeme11.pgn
wget http://www.chess88.net/pgn/cheurindw11.pgn
wget http://www.chess88.net/pgn/lublingm11.pgn
wget http://www.chess88.net/pgn/capmemp11.pgn
wget http://www.chess88.net/pgn/danzhougm11.pgn
wget http://www.chess88.net/pgn/capmemopa11.pgn
wget http://www.chess88.net/pgn/capmemopb11.pgn
wget http://www.chess88.net/pgn/nakapono11.pgn
wget http://www.chess88.net/pgn/robfin11.pgn
wget http://www.chess88.net/pgn/nakaponor11.pgn
wget http://www.chess88.net/pgn/robfinr11.pgn
wget http://www.chess88.net/pgn/chger11.pgn
wget http://www.chess88.net/pgn/tchfratop1211.pgn
wget http://www.chess88.net/pgn/leonm11.pgn
wget http://www.chess88.net/pgn/sige11.pgn
wget http://www.chess88.net/pgn/chukr11.pgn
wget http://www.chess88.net/pgn/medias11.pgn
wget http://www.chess88.net/pgn/chnceleb11.pgn
wget http://www.chess88.net/pgn/cez11.pgn
wget http://www.chess88.net/pgn/chrushl11.pgn
wget http://www.chess88.net/pgn/chrushlw11.pgn
wget http://www.chess88.net/pgn/marxmem11.pgn
wget http://www.chess88.net/pgn/marxmemwgm11.pgn
wget http://www.chess88.net/pgn/pulaop11.pgn
wget http://www.chess88.net/pgn/aaigm11.pgn
wget http://www.chess88.net/pgn/chned11.pgn
wget http://www.chess88.net/pgn/common11.pgn
wget http://www.chess88.net/pgn/chnedw11.pgn
wget http://www.chess88.net/pgn/worldop11.pgn
wget http://www.chess88.net/pgn/bigslickgm11.pgn
wget http://www.chess88.net/pgn/chusajun11.pgn
wget http://www.chess88.net/pgn/bigslickim11.pgn
wget http://www.chess88.net/pgn/chchnrapmp11.pgn
wget http://www.chess88.net/pgn/chchnrapwp11.pgn
wget http://www.chess88.net/pgn/chchnrapmko11.pgn
wget http://www.chess88.net/pgn/chchnrapwko11.pgn
wget http://www.chess88.net/pgn/tchgre11.pgn
wget http://www.chess88.net/pgn/amsterdamspa11.pgn
wget http://www.chess88.net/pgn/chsco11.pgn
wget http://www.chess88.net/pgn/lctop11.pgn
wget http://www.chess88.net/pgn/hangzwgm11.pgn
wget http://www.chess88.net/pgn/heartfin11.pgn
wget http://www.chess88.net/pgn/wteam11.pgn
wget http://www.chess88.net/pgn/bielmast11.pgn
wget http://www.chess88.net/pgn/opennk11.pgn
wget http://www.chess88.net/pgn/bielmto11.pgn
wget http://www.chess88.net/pgn/dort11.pgn
wget http://www.chess88.net/pgn/andop11.pgn
wget http://www.chess88.net/pgn/rostovwgp11.pgn
wget http://www.chess88.net/pgn/chgbr11.pgn
wget http://www.chess88.net/pgn/usop11.pgn
wget http://www.chess88.net/pgn/chgbrp11.pgn
wget http://www.chess88.net/pgn/hzop11.pgn
wget http://www.chess88.net/pgn/navalazn11.pgn
wget http://www.chess88.net/pgn/wjun11.pgn
wget http://www.chess88.net/pgn/wjung11.pgn
wget http://www.chess88.net/pgn/chrus11.pgn
wget http://www.chess88.net/pgn/bakuop11.pgn
wget http://www.chess88.net/pgn/chfra11.pgn
wget http://www.chess88.net/pgn/chfraw11.pgn
wget http://www.chess88.net/pgn/chfrab11.pgn
wget http://www.chess88.net/pgn/manhemgm11.pgn
wget http://www.chess88.net/pgn/botcentop11.pgn
wget http://www.chess88.net/pgn/chrusw11.pgn
wget http://www.chess88.net/pgn/universiademen11.pgn
wget http://www.chess88.net/pgn/universiadewomen11.pgn
wget http://www.chess88.net/pgn/botvinmems11.pgn
wget http://www.chess88.net/pgn/santsop11.pgn
wget http://www.chess88.net/pgn/wcup11.pgn
wget http://www.chess88.net/pgn/malayop11.pgn
wget http://www.chess88.net/pgn/botvinmem11.pgn
wget http://www.chess88.net/pgn/botvinmemw11.pgn
wget http://www.chess88.net/pgn/shenzwgp11.pgn
wget http://www.chess88.net/pgn/kaspclich11.pgn
wget http://www.chess88.net/pgn/moscstp11.pgn
wget http://www.chess88.net/pgn/kaspclichq11.pgn
wget http://www.chess88.net/pgn/ecc11.pgn
wget http://www.chess88.net/pgn/eccw11.pgn
wget http://www.chess88.net/pgn/finalmast11.pgn
wget http://www.chess88.net/pgn/poik11.pgn
wget http://www.chess88.net/pgn/finalmastp11.pgn
wget http://www.chess88.net/pgn/nalchikwgp11.pgn
wget http://www.chess88.net/pgn/kaspshort11.pgn
wget http://www.chess88.net/pgn/saratovcup11.pgn
wget http://www.chess88.net/pgn/casinobarc11.pgn
wget http://www.chess88.net/pgn/bund1112.pgn
wget http://www.chess88.net/pgn/univeop11.pgn
wget http://www.chess88.net/pgn/univecr11.pgn
wget http://www.chess88.net/pgn/spicecupa11.pgn
wget http://www.chess88.net/pgn/spicecupb11.pgn
wget http://www.chess88.net/pgn/spicecupc11.pgn
wget http://www.chess88.net/pgn/tcheurop11.pgn
wget http://www.chess88.net/pgn/wchw11.pgn
wget http://www.chess88.net/pgn/tcheurw11.pgn
wget http://www.chess88.net/pgn/ruscupf11.pgn
wget http://www.chess88.net/pgn/ruscupfw11.pgn
wget http://www.chess88.net/pgn/euwemem111.pgn
wget http://www.chess88.net/pgn/euwemem211.pgn
wget http://www.chess88.net/pgn/talmem11.pgn
wget http://www.chess88.net/pgn/loncc11.pgn
wget http://www.chess88.net/pgn/sportaccordfr11.pgn
wget http://www.chess88.net/pgn/sportaccordfrw11.pgn
wget http://www.chess88.net/pgn/sportaccbfold11.pgn
wget http://www.chess88.net/pgn/sportaccbfoldw11.pgn
wget http://www.chess88.net/pgn/wteamw11.pgn
wget http://www.chess88.net/pgn/cheurra11.pgn
wget http://www.chess88.net/pgn/groninga11.pgn
wget http://www.chess88.net/pgn/cheurbl11.pgn
wget http://www.chess88.net/pgn/reggio1112.pgn
wget http://www.chess88.net/pgn/reggiow1112.pgn
wget http://www.chess88.net/pgn/hastm1112.pgn
wget http://www.chess88.net/pgn/donostia11.pgn
wget http://www.chess88.net/pgn/wijka12.pgn
wget http://www.chess88.net/pgn/wijkb12.pgn
wget http://www.chess88.net/pgn/wijkc12.pgn
wget http://www.chess88.net/pgn/keresmemp12.pgn
wget http://www.chess88.net/pgn/queenst12.pgn
wget http://www.chess88.net/pgn/keresmemf12.pgn
wget http://www.chess88.net/pgn/gibral12.pgn
wget http://www.chess88.net/pgn/aeroa12.pgn
wget http://www.chess88.net/pgn/acpwomcup12.pgn
wget http://www.chess88.net/pgn/petrovmemp12.pgn
wget http://www.chess88.net/pgn/bunrat12.pgn
wget http://www.chess88.net/pgn/petrovmemf12.pgn
wget http://www.chess88.net/pgn/chebmemko12.pgn
wget http://www.chess88.net/pgn/cheurindw12.pgn
wget http://www.chess88.net/pgn/chger12.pgn
wget http://www.chess88.net/pgn/cappellop12.pgn
wget http://www.chess88.net/pgn/reykop12.pgn
wget http://www.chess88.net/pgn/cheurind12.pgn
wget http://www.chess88.net/pgn/chchn12.pgn
wget http://www.chess88.net/pgn/chchnw12.pgn
wget http://www.chess88.net/pgn/chden12.pgn
wget http://www.chess88.net/pgn/tchrus12.pgn
wget http://www.chess88.net/pgn/tchrusw12.pgn
wget http://www.chess88.net/pgn/bangkokop12.pgn
wget http://www.chess88.net/pgn/arokra12.pgn
wget http://www.chess88.net/pgn/dubaiop12.pgn
wget http://www.chess88.net/pgn/wommastchn12.pgn
wget http://www.chess88.net/pgn/capmeme12.pgn
wget http://www.chess88.net/pgn/chusa12.pgn
wget http://www.chess88.net/pgn/capmemp12.pgn
wget http://www.chess88.net/pgn/chusaw12.pgn
wget http://www.chess88.net/pgn/wch12.pgn
wget http://www.chess88.net/pgn/sige12.pgn
wget http://www.chess88.net/pgn/wchrp12.pgn
wget http://www.chess88.net/pgn/chusawp12.pgn
wget http://www.chess88.net/pgn/tchfratop12.pgn
wget http://www.chess88.net/pgn/talmembl12.pgn
wget http://www.chess88.net/pgn/talmem12.pgn
wget http://www.chess88.net/pgn/kazanwgp12.pgn
wget http://www.chess88.net/pgn/wchrapw12.pgn
wget http://www.chess88.net/pgn/karseircl12.pgn
wget http://www.chess88.net/pgn/karseirbl12.pgn
wget http://www.chess88.net/pgn/karseirrap12.pgn
wget http://www.chess88.net/pgn/chrushl12.pgn
wget http://www.chess88.net/pgn/chrushlw12.pgn
wget http://www.chess88.net/pgn/cez12.pgn
wget http://www.chess88.net/pgn/tchchn12.pgn
wget http://www.chess88.net/pgn/ruschnmcl12.pgn
wget http://www.chess88.net/pgn/ruschnmclw12.pgn
wget http://www.chess88.net/pgn/wrapidf12.pgn
wget http://www.chess88.net/pgn/wblitzf12.pgn
wget http://www.chess88.net/pgn/dort12.pgn
wget http://www.chess88.net/pgn/chsco12.pgn
wget http://www.chess88.net/pgn/acpgold12.pgn
wget http://www.chess88.net/pgn/chned12.pgn
wget http://www.chess88.net/pgn/amstsciparkopa12.pgn
wget http://www.chess88.net/pgn/chnedw12.pgn
wget http://www.chess88.net/pgn/jermukwgp12.pgn
wget http://www.chess88.net/pgn/bielexblitz12.pgn
wget http://www.chess88.net/pgn/chgbr12.pgn
wget http://www.chess88.net/pgn/bielgm12.pgn
wget http://www.chess88.net/pgn/chgbrp12.pgn
wget http://www.chess88.net/pgn/chrus12.pgn
wget http://www.chess88.net/pgn/wjun12.pgn
wget http://www.chess88.net/pgn/chrusw12.pgn
wget http://www.chess88.net/pgn/wjung12.pgn
wget http://www.chess88.net/pgn/chrusp12.pgn
wget http://www.chess88.net/pgn/chfra12.pgn
wget http://www.chess88.net/pgn/chfraw12.pgn
wget http://www.chess88.net/pgn/olymm12.pgn
wget http://www.chess88.net/pgn/olymw12.pgn
wget http://www.chess88.net/pgn/blacksea12.pgn
wget http://www.chess88.net/pgn/ankarawgp12.pgn
wget http://www.chess88.net/pgn/londongp12.pgn
wget http://www.chess88.net/pgn/finalmaster12.pgn
wget http://www.chess88.net/pgn/poikgm12.pgn
wget http://www.chess88.net/pgn/stpcuprap12.pgn
wget http://www.chess88.net/pgn/ecc12.pgn
wget http://www.chess88.net/pgn/eccw12.pgn
wget http://www.chess88.net/pgn/spicecupgm12.pgn
wget http://www.chess88.net/pgn/finalmasterp12.pgn
wget http://www.chess88.net/pgn/spicecupop12.pgn
wget http://www.chess88.net/pgn/univecr12.pgn
wget http://www.chess88.net/pgn/casinobarc12.pgn
wget http://www.chess88.net/pgn/univeop12.pgn
wget http://www.chess88.net/pgn/chigmem12.pgn
wget http://www.chess88.net/pgn/chigmemr12.pgn
wget http://www.chess88.net/pgn/andrnepom12.pgn
wget http://www.chess88.net/pgn/chita12.pgn
wget http://www.chess88.net/pgn/trophykarpov12.pgn
wget http://www.chess88.net/pgn/trophykarpovko12.pgn
wget http://www.chess88.net/pgn/corsicamastop12.pgn
wget http://www.chess88.net/pgn/corsicamastko12.pgn
wget http://www.chess88.net/pgn/tchespceclubh12.pgn
wget http://www.chess88.net/pgn/kings12.pgn
wget http://www.chess88.net/pgn/wcupw12.pgn
wget http://www.chess88.net/pgn/kingsp12.pgn
wget http://www.chess88.net/pgn/sibbank12.pgn
wget http://www.chess88.net/pgn/remcoheiteinv12.pgn
wget http://www.chess88.net/pgn/kosticmem12.pgn
wget http://www.chess88.net/pgn/remcoheite12.pgn
wget http://www.chess88.net/pgn/tashkentgp12.pgn
wget http://www.chess88.net/pgn/kilkennymast12.pgn
wget http://www.chess88.net/pgn/loncc12.pgn
wget http://www.chess88.net/pgn/lonccop12.pgn
wget http://www.chess88.net/pgn/sportaccordrap12.pgn
wget http://www.chess88.net/pgn/eurrap12.pgn
wget http://www.chess88.net/pgn/eurbli12.pgn
wget http://www.chess88.net/pgn/sportaccordbli12.pgn
wget http://www.chess88.net/pgn/sportaccordbliw12.pgn
wget http://www.chess88.net/pgn/sportaccordbf12.pgn
wget http://www.chess88.net/pgn/sportaccordbfw12.pgn
wget http://www.chess88.net/pgn/worldcit12.pgn
wget http://www.chess88.net/pgn/alalinclass12.pgn
wget http://www.chess88.net/pgn/rilt1213.pgn
wget http://www.chess88.net/pgn/gronigenopa12.pgn
wget http://www.chess88.net/pgn/aicfaaicup12.pgn
wget http://www.chess88.net/pgn/gronigencc12.pgn
wget http://www.chess88.net/pgn/hastmast1213.pgn
wget http://www.chess88.net/pgn/baselfest13.pgn
wget http://www.chess88.net/pgn/wijka13.pgn
wget http://www.chess88.net/pgn/wijkc13.pgn
wget http://www.chess88.net/pgn/wijkb13.pgn
wget http://www.chess88.net/pgn/gibralmast13.pgn
wget http://www.chess88.net/pgn/badencc13.pgn
wget http://www.chess88.net/pgn/gibralmasttb13.pgn
wget http://www.chess88.net/pgn/moscopa13.pgn
wget http://www.chess88.net/pgn/moscopf13.pgn
wget http://www.chess88.net/pgn/moscopb13.pgn
wget http://www.chess88.net/pgn/moscopg13.pgn
wget http://www.chess88.net/pgn/badenop13.pgn
wget http://www.chess88.net/pgn/aerooprapq13.pgn
wget http://www.chess88.net/pgn/petrovmem13.pgn
wget http://www.chess88.net/pgn/aerooprapko13.pgn
wget http://www.chess88.net/pgn/reykop13.pgn
wget http://www.chess88.net/pgn/aerooprap13.pgn
wget http://www.chess88.net/pgn/zuerichcc13.pgn
wget http://www.chess88.net/pgn/zuerichccb13.pgn
wget http://www.chess88.net/pgn/cappelleop13.pgn
wget http://www.chess88.net/pgn/bunratmast13.pgn
wget http://www.chess88.net/pgn/worldteamw13.pgn
wget http://www.chess88.net/pgn/wchcand13.pgn
wget http://www.chess88.net/pgn/tchrus13.pgn
wget http://www.chess88.net/pgn/tchrusw13.pgn
wget http://www.chess88.net/pgn/chchn13.pgn
wget http://www.chess88.net/pgn/chisr13.pgn
wget http://www.chess88.net/pgn/chchnw13.pgn
wget http://www.chess88.net/pgn/chisrw13.pgn
wget http://www.chess88.net/pgn/bccop13.pgn
wget http://www.chess88.net/pgn/zuggp13.pgn
wget http://www.chess88.net/pgn/alekmem13.pgn
wget http://www.chess88.net/pgn/capmeme13.pgn
wget http://www.chess88.net/pgn/chusa13.pgn
wget http://www.chess88.net/pgn/genevawgp13.pgn
wget http://www.chess88.net/pgn/chusaw13.pgn
wget http://www.chess88.net/pgn/cheurindiv13.pgn
wget http://www.chess88.net/pgn/norwaysup13.pgn
wget http://www.chess88.net/pgn/norwaysupbl13.pgn
wget http://www.chess88.net/pgn/chusap13.pgn
wget http://www.chess88.net/pgn/danzhougm13.pgn
wget http://www.chess88.net/pgn/sige13.pgn
wget http://www.chess88.net/pgn/thessgp13.pgn
wget http://www.chess88.net/pgn/sberbankgmrap13.pgn
wget http://www.chess88.net/pgn/tchfratop1213.pgn
wget http://www.chess88.net/pgn/talmem13.pgn
wget http://www.chess88.net/pgn/cez13.pgn
wget http://www.chess88.net/pgn/wrap13.pgn
wget http://www.chess88.net/pgn/chukr13.pgn
wget http://www.chess88.net/pgn/wblit13.pgn
wget http://www.chess88.net/pgn/dilijanwgp13.pgn
wget http://www.chess88.net/pgn/chrushl13.pgn
wget http://www.chess88.net/pgn/carlsenpred13.pgn
wget http://www.chess88.net/pgn/chnor13.pgn
wget http://www.chess88.net/pgn/genevamgpa13.pgn
wget http://www.chess88.net/pgn/genevamko13.pgn
wget http://www.chess88.net/pgn/genevamgpb13.pgn
wget http://www.chess88.net/pgn/genevaopa13.pgn
wget http://www.chess88.net/pgn/beijinggp13.pgn
wget http://www.chess88.net/pgn/chned13.pgn
wget http://www.chess88.net/pgn/chnedw13.pgn
wget http://www.chess88.net/pgn/universiadem13.pgn
wget http://www.chess88.net/pgn/lct13.pgn
wget http://www.chess88.net/pgn/chnusamcl13.pgn
wget http://www.chess88.net/pgn/bielgm13.pgn
wget http://www.chess88.net/pgn/chnusamra13.pgn
wget http://www.chess88.net/pgn/bielmaster13.pgn
wget http://www.chess88.net/pgn/czechopa13.pgn
wget http://www.chess88.net/pgn/cheurindw13.pgn
wget http://www.chess88.net/pgn/dort13.pgn
wget http://www.chess88.net/pgn/chgbr13.pgn
wget http://www.chess88.net/pgn/hzop13.pgn
wget http://www.chess88.net/pgn/bielgmp13.pgn
wget http://www.chess88.net/pgn/rigatech13.pgn
wget http://www.chess88.net/pgn/wcup13.pgn
wget http://www.chess88.net/pgn/poikgm13.pgn
wget http://www.chess88.net/pgn/chfra13.pgn
wget http://www.chess88.net/pgn/sinqcup13.pgn
wget http://www.chess88.net/pgn/wchw13.pgn
wget http://www.chess88.net/pgn/tashkentwgp13.pgn
wget http://www.chess88.net/pgn/toplazm13.pgn
wget http://www.chess88.net/pgn/parigp13.pgn
wget http://www.chess88.net/pgn/reykgm13.pgn
wget http://www.chess88.net/pgn/chrussup13.pgn
wget http://www.chess88.net/pgn/kings13.pgn
wget http://www.chess88.net/pgn/chrussupw13.pgn
wget http://www.chess88.net/pgn/bilbaomast13.pgn
wget http://www.chess88.net/pgn/chrussupp13.pgn
wget http://www.chess88.net/pgn/ecc13.pgn
wget http://www.chess88.net/pgn/eccw13.pgn
wget http://www.chess88.net/pgn/univecr13.pgn
wget http://www.chess88.net/pgn/univeop13.pgn
wget http://www.chess88.net/pgn/karptropp13.pgn
wget http://www.chess88.net/pgn/karpovtropp13.pgn
wget http://www.chess88.net/pgn/karptropko13.pgn
wget http://www.chess88.net/pgn/karpovtrop213.pgn
wget http://www.chess88.net/pgn/wch13.pgn
wget http://www.chess88.net/pgn/tcheur13.pgn
wget http://www.chess88.net/pgn/worldteam13.pgn
wget http://www.chess88.net/pgn/tcheurw13.pgn
wget http://www.chess88.net/pgn/dubshim13.pgn
wget http://www.chess88.net/pgn/londccko13.pgn
wget http://www.chess88.net/pgn/hastings1314.pgn
wget http://www.chess88.net/pgn/lonccop13.pgn
wget http://www.chess88.net/pgn/riltcup1314.pgn
wget http://www.chess88.net/pgn/zurichch13.pgn
wget http://www.chess88.net/pgn/gronop13.pgn
wget http://www.chess88.net/pgn/tatagpa14.pgn
wget http://www.chess88.net/pgn/gibralmast14.pgn
wget http://www.chess88.net/pgn/tatagpb14.pgn
wget http://www.chess88.net/pgn/zurichccc14.pgn
wget http://www.chess88.net/pgn/zurichccr14.pgn
wget http://www.chess88.net/pgn/bunrat14.pgn
wget http://www.chess88.net/pgn/cappelleop14.pgn
wget http://www.chess88.net/pgn/cheurind14.pgn
wget http://www.chess88.net/pgn/reykop14.pgn
wget http://www.chess88.net/pgn/chchn14.pgn
wget http://www.chess88.net/pgn/wchcand14.pgn
wget http://www.chess88.net/pgn/hdbank14.pgn
wget http://www.chess88.net/pgn/chchnw14.pgn
wget http://www.chess88.net/pgn/tchrus14.pgn
wget http://www.chess88.net/pgn/dubaiop14.pgn
wget http://www.chess88.net/pgn/tchrusw14.pgn
wget http://www.chess88.net/pgn/kmwgp14.pgn
wget http://www.chess88.net/pgn/gashmem14.pgn
wget http://www.chess88.net/pgn/asiancont14.pgn
wget http://www.chess88.net/pgn/gashmemb14.pgn
wget http://www.chess88.net/pgn/wrapw14.pgn
wget http://www.chess88.net/pgn/sydneyop14.pgn
wget http://www.chess88.net/pgn/chcze14.pgn
wget http://www.chess88.net/pgn/portrapp14.pgn
wget http://www.chess88.net/pgn/tchita14.pgn
wget http://www.chess88.net/pgn/chnwmast14.pgn
wget http://www.chess88.net/pgn/nalhp14.pgn
wget http://www.chess88.net/pgn/lublingm14.pgn
wget http://www.chess88.net/pgn/chusa14.pgn
wget http://www.chess88.net/pgn/carlsennor14.pgn
wget http://www.chess88.net/pgn/chusaw14.pgn
wget http://www.chess88.net/pgn/capmeme14.pgn
wget http://www.chess88.net/pgn/poikgm14.pgn
wget http://www.chess88.net/pgn/chusatb14.pgn
wget http://www.chess88.net/pgn/chusatbw14.pgn
wget http://www.chess88.net/pgn/asiannat14.pgn
wget http://www.chess88.net/pgn/asiannatw14.pgn
wget http://www.chess88.net/pgn/chisl14.pgn
wget http://www.chess88.net/pgn/tchfra14.pgn
wget http://www.chess88.net/pgn/zalaop14.pgn
wget http://www.chess88.net/pgn/stlouisinvgm14.pgn
wget http://www.chess88.net/pgn/wunsiedelop14.pgn
wget http://www.chess88.net/pgn/norwaybl14.pgn
wget http://www.chess88.net/pgn/chrushl14.pgn
wget http://www.chess88.net/pgn/norway14.pgn
wget http://www.chess88.net/pgn/chrushlw14.pgn
wget http://www.chess88.net/pgn/cez14.pgn
wget http://www.chess88.net/pgn/hunpolm14.pgn
wget http://www.chess88.net/pgn/voronop14.pgn
wget http://www.chess88.net/pgn/wrap14.pgn
wget http://www.chess88.net/pgn/wbli14.pgn
wget http://www.chess88.net/pgn/lopotawgp14.pgn
wget http://www.chess88.net/pgn/chisr14.pgn
wget http://www.chess88.net/pgn/hsgop14.pgn
wget http://www.chess88.net/pgn/hmccald14.pgn
wget http://www.chess88.net/pgn/edmontgm14.pgn
wget http://www.chess88.net/pgn/chusajun14.pgn
wget http://www.chess88.net/pgn/haindan14.pgn
wget http://www.chess88.net/pgn/vismagm14.pgn
wget http://www.chess88.net/pgn/tchtur14.pgn
wget http://www.chess88.net/pgn/polumem14.pgn
wget http://www.chess88.net/pgn/chned14.pgn
wget http://www.chess88.net/pgn/commonw14.pgn
wget http://www.chess88.net/pgn/dort14.pgn
wget http://www.chess88.net/pgn/chnor14.pgn
wget http://www.chess88.net/pgn/acpgold14.pgn
wget http://www.chess88.net/pgn/chswe14.pgn
wget http://www.chess88.net/pgn/lct14.pgn
wget http://www.chess88.net/pgn/nanaalek14.pgn
wget http://www.chess88.net/pgn/bielgm14.pgn
wget http://www.chess88.net/pgn/najmema14.pgn
wget http://www.chess88.net/pgn/corpcup14.pgn
wget http://www.chess88.net/pgn/japhetop14.pgn
wget http://www.chess88.net/pgn/charg14.pgn
wget http://www.chess88.net/pgn/bergamoop14.pgn
wget http://www.chess88.net/pgn/czechopa14.pgn
wget http://www.chess88.net/pgn/cheurw14.pgn
wget http://www.chess88.net/pgn/chgbr14.pgn
wget http://www.chess88.net/pgn/gelsvir14.pgn
wget http://www.chess88.net/pgn/politcup14.pgn
wget http://www.chess88.net/pgn/dutchop14.pgn
wget http://www.chess88.net/pgn/tamincoop14.pgn
wget http://www.chess88.net/pgn/lakesevan14.pgn
wget http://www.chess88.net/pgn/primdeb14.pgn
wget http://www.chess88.net/pgn/tchchn14.pgn
wget http://www.chess88.net/pgn/ideonop14.pgn
wget http://www.chess88.net/pgn/olym14.pgn
wget http://www.chess88.net/pgn/olomgm14.pgn
wget http://www.chess88.net/pgn/olymw14.pgn
wget http://www.chess88.net/pgn/hzop14.pgn
wget http://www.chess88.net/pgn/abudmast14.pgn
wget http://www.chess88.net/pgn/rigatechopa14.pgn
wget http://www.chess88.net/pgn/chfra14.pgn
wget http://www.chess88.net/pgn/zmdiop14.pgn
wget http://www.chess88.net/pgn/santsop14.pgn
wget http://www.chess88.net/pgn/portosang14.pgn
wget http://www.chess88.net/pgn/charm114.pgn
wget http://www.chess88.net/pgn/sharjahwgp14.pgn
wget http://www.chess88.net/pgn/chesp14.pgn
wget http://www.chess88.net/pgn/yarorap14.pgn
wget http://www.chess88.net/pgn/tchtursup14.pgn
wget http://www.chess88.net/pgn/sinqcup14.pgn
wget http://www.chess88.net/pgn/strap14.pgn
wget http://www.chess88.net/pgn/tchesphon14.pgn
wget http://www.chess88.net/pgn/ecocup14.pgn
wget http://www.chess88.net/pgn/grenke14.pgn
wget http://www.chess88.net/pgn/bilbaomast14.pgn
wget http://www.chess88.net/pgn/zudovmem14.pgn
wget http://www.chess88.net/pgn/ecc14.pgn
wget http://www.chess88.net/pgn/gaprindcup14.pgn
wget http://www.chess88.net/pgn/eccwom14.pgn
wget http://www.chess88.net/pgn/chsui14.pgn
wget http://www.chess88.net/pgn/shisverap14.pgn
wget http://www.chess88.net/pgn/osloint14.pgn
wget http://www.chess88.net/pgn/bakugp14.pgn
wget http://www.chess88.net/pgn/raplazm14.pgn
wget http://www.chess88.net/pgn/iommast14.pgn
wget http://www.chess88.net/pgn/wjun14.pgn
wget http://www.chess88.net/pgn/millioneop14.pgn
wget http://www.chess88.net/pgn/wjung14.pgn
wget http://www.chess88.net/pgn/tchmosc14.pgn
wget http://www.chess88.net/pgn/milliontb14.pgn
wget http://www.chess88.net/pgn/univegs14.pgn
wget http://www.chess88.net/pgn/millionko14.pgn
wget http://www.chess88.net/pgn/univetj14.pgn
wget http://www.chess88.net/pgn/univeop14.pgn
wget http://www.chess88.net/pgn/chigmem14.pgn
wget http://www.chess88.net/pgn/oscaroop14.pgn
wget http://www.chess88.net/pgn/tashkentgp14.pgn
wget http://www.chess88.net/pgn/corsecirfin14.pgn
wget http://www.chess88.net/pgn/petrosianmem14.pgn
wget http://www.chess88.net/pgn/wsenm5014.pgn
wget http://www.chess88.net/pgn/2014chn_zonal.pgn
wget http://www.chess88.net/pgn/wch14.pgn
wget http://www.chess88.net/pgn/chukr14.pgn
wget http://www.chess88.net/pgn/ugragovcup14.pgn
wget http://www.chess88.net/pgn/chukrw14.pgn
wget http://www.chess88.net/pgn/talmemb14.pgn
wget http://www.chess88.net/pgn/remcogm14.pgn
wget http://www.chess88.net/pgn/nakaaron14.pgn
wget http://www.chess88.net/pgn/kingsrouchn14.pgn
wget http://www.chess88.net/pgn/qatmast14.pgn
wget http://www.chess88.net/pgn/chita14.pgn
wget http://www.chess88.net/pgn/chrussf14.pgn
wget http://www.chess88.net/pgn/barcgm14.pgn
wget http://www.chess88.net/pgn/chrussfw14.pgn
wget http://www.chess88.net/pgn/chgre6414.pgn
wget http://www.chess88.net/pgn/lonccrap14.pgn
wget http://www.chess88.net/pgn/lonccbli14.pgn
wget http://www.chess88.net/pgn/lonccop14.pgn
wget http://www.chess88.net/pgn/lonccm14.pgn
wget http://www.chess88.net/pgn/loncc14.pgn
wget http://www.chess88.net/pgn/wyco14.pgn
wget http://www.chess88.net/pgn/sportaccrap14.pgn
wget http://www.chess88.net/pgn/sportaccrapw14.pgn
wget http://www.chess88.net/pgn/sportaccbl14.pgn
wget http://www.chess88.net/pgn/sportaccblw14.pgn
wget http://www.chess88.net/pgn/sportaccbas14.pgn
wget http://www.chess88.net/pgn/sportaccbasw14.pgn
wget http://www.chess88.net/pgn/riltcup1415.pgn
wget http://www.chess88.net/pgn/gronop14.pgn
wget http://www.chess88.net/pgn/hastm14.pgn
wget http://www.chess88.net/pgn/alain14.pgn
wget http://www.chess88.net/pgn/tatagma15.pgn
wget http://www.chess88.net/pgn/alainr14.pgn
wget http://www.chess88.net/pgn/tatagmb15.pgn
wget http://www.chess88.net/pgn/ausop15.pgn
wget http://www.chess88.net/pgn/gibralmast15.pgn
wget http://www.chess88.net/pgn/moscoopa15.pgn
wget http://www.chess88.net/pgn/moscoopw15.pgn
wget http://www.chess88.net/pgn/grenketb15.pgn
wget http://www.chess88.net/pgn/moscoopstw15.pgn
wget http://www.chess88.net/pgn/aarhuschgm15.pgn
wget http://www.chess88.net/pgn/moscoopst15.pgn
wget http://www.chess88.net/pgn/zurichccb15.pgn
wget http://www.chess88.net/pgn/tbilisigp15.pgn
wget http://www.chess88.net/pgn/zurichcc15.pgn
wget http://www.chess88.net/pgn/noteboom15.pgn
wget http://www.chess88.net/pgn/zurichccr15.pgn
wget http://www.chess88.net/pgn/noteboomop15.pgn
wget http://www.chess88.net/pgn/zurichcctb15.pgn
wget http://www.chess88.net/pgn/zurichccku15.pgn
wget http://www.chess88.net/pgn/bunratc15.pgn
wget http://www.chess88.net/pgn/bunrat15.pgn
wget http://www.chess88.net/pgn/bund1415.pgn
wget http://www.chess88.net/pgn/bataviagm15.pgn
wget http://www.chess88.net/pgn/cappelleop15.pgn
wget http://www.chess88.net/pgn/cheurind15.pgn
wget http://www.chess88.net/pgn/indchnsummit15.pgn
wget http://www.chess88.net/pgn/petrovmemb15.pgn
wget http://www.chess88.net/pgn/reykop15.pgn
wget http://www.chess88.net/pgn/petrovmem15.pgn
wget http://www.chess88.net/pgn/wchwko15.pgn
wget http://www.chess88.net/pgn/hdbank15.pgn
wget http://www.chess88.net/pgn/chpol15.pgn
wget http://www.chess88.net/pgn/kolkop15.pgn
wget http://www.chess88.net/pgn/aeroflotopa15.pgn
wget http://www.chess88.net/pgn/chusa15.pgn
wget http://www.chess88.net/pgn/dubaiop15.pgn
wget http://www.chess88.net/pgn/chusaw15.pgn
wget http://www.chess88.net/pgn/bccop15.pgn
wget http://www.chess88.net/pgn/gashmem15.pgn
wget http://www.chess88.net/pgn/wteamw15.pgn
wget http://www.chess88.net/pgn/worldteam15.pgn
wget http://www.chess88.net/pgn/kaspshortr15.pgn
wget http://www.chess88.net/pgn/kaspshortb15.pgn
wget http://www.chess88.net/pgn/tchrusm15.pgn
wget http://www.chess88.net/pgn/tchrusw15.pgn
wget http://www.chess88.net/pgn/tchrusrap15.pgn
wget http://www.chess88.net/pgn/scanmast15.pgn
wget http://www.chess88.net/pgn/kmgp15.pgn
wget http://www.chess88.net/pgn/scanmastrap15.pgn
wget http://www.chess88.net/pgn/chisl15.pgn
wget http://www.chess88.net/pgn/chchn15.pgn
wget http://www.chess88.net/pgn/limburgop15.pgn
wget http://www.chess88.net/pgn/chchnw15.pgn
wget http://www.chess88.net/pgn/tchfra15.pgn
wget http://www.chess88.net/pgn/tchchn15.pgn
wget http://www.chess88.net/pgn/norway15.pgn
wget http://www.chess88.net/pgn/capmemp15.pgn
wget http://www.chess88.net/pgn/asrianmem15.pgn
wget http://www.chess88.net/pgn/capmeme15.pgn
wget http://www.chess88.net/pgn/edmontgm15.pgn
wget http://www.chess88.net/pgn/chrushl15.pgn
wget http://www.chess88.net/pgn/dort15.pgn
wget http://www.chess88.net/pgn/haindan15.pgn
wget http://www.chess88.net/pgn/porticcioop15.pgn
wget http://www.chess88.net/pgn/karsverap15.pgn
wget http://www.chess88.net/pgn/polumem15.pgn
wget http://www.chess88.net/pgn/chned15.pgn
wget http://www.chess88.net/pgn/nanaalek15.pgn
wget http://www.chess88.net/pgn/najmema15.pgn
wget http://www.chess88.net/pgn/lakesevan15.pgn
wget http://www.chess88.net/pgn/chnrus15.pgn
wget http://www.chess88.net/pgn/dinggelf15.pgn
wget http://www.chess88.net/pgn/chnrusw15.pgn
wget http://www.chess88.net/pgn/bielgm15.pgn
wget http://www.chess88.net/pgn/ghentop15.pgn
wget http://www.chess88.net/pgn/andop15.pgn
wget http://www.chess88.net/pgn/czechopa15.pgn
wget http://www.chess88.net/pgn/dutchop15.pgn
wget http://www.chess88.net/pgn/lct15.pgn
wget http://www.chess88.net/pgn/politcup15.pgn
wget http://www.chess88.net/pgn/chgbr15.pgn
wget http://www.chess88.net/pgn/hzop15.pgn
wget http://www.chess88.net/pgn/chnruswc15.pgn
wget http://www.chess88.net/pgn/chrus15.pgn
wget http://www.chess88.net/pgn/chfra15.pgn
wget http://www.chess88.net/pgn/chrusw15.pgn
wget http://www.chess88.net/pgn/chfraw15.pgn
wget http://www.chess88.net/pgn/rigatechopa15.pgn
wget http://www.chess88.net/pgn/tchtursup15.pgn
wget http://www.chess88.net/pgn/tchesphon15.pgn
wget http://www.chess88.net/pgn/sinqcup15.pgn
wget http://www.chess88.net/pgn/wjun15.pgn
wget http://www.chess88.net/pgn/abudmast15.pgn
wget http://www.chess88.net/pgn/wjung15.pgn
wget http://www.chess88.net/pgn/tchpole15.pgn
wget http://www.chess88.net/pgn/moscbli15.pgn
wget http://www.chess88.net/pgn/wcup15.pgn
wget http://www.chess88.net/pgn/mcarlowgp15.pgn
wget http://www.chess88.net/pgn/iommast15.pgn
wget http://www.chess88.net/pgn/poikgm15.pgn
wget http://www.chess88.net/pgn/millioneop15.pgn
wget http://www.chess88.net/pgn/wrap15.pgn
wget http://www.chess88.net/pgn/wbli15.pgn
wget http://www.chess88.net/pgn/millionko15.pgn
wget http://www.chess88.net/pgn/ecc15.pgn
wget http://www.chess88.net/pgn/eccw15.pgn
wget http://www.chess88.net/pgn/bilbaomast15.pgn
wget http://www.chess88.net/pgn/chibam15.pgn
wget http://www.chess88.net/pgn/barcgm15.pgn
wget http://www.chess88.net/pgn/britrap15.pgn
wget http://www.chess88.net/pgn/tcheur15.pgn
wget http://www.chess88.net/pgn/tcheurw15.pgn
wget http://www.chess88.net/pgn/loncc15.pgn
wget http://www.chess88.net/pgn/lonccop15.pgn
wget http://www.chess88.net/pgn/ruscup15.pgn
wget http://www.chess88.net/pgn/ruscupw15.pgn
wget http://www.chess88.net/pgn/loncctb15.pgn
wget http://www.chess88.net/pgn/qatmast15.pgn
wget http://www.chess88.net/pgn/alain15.pgn
wget http://www.chess88.net/pgn/zurichch15.pgn
wget http://www.chess88.net/pgn/qatmasttb15.pgn
wget http://www.chess88.net/pgn/riltcup1516.pgn
wget http://www.chess88.net/pgn/hastm15.pgn
wget http://www.chess88.net/pgn/keresmem16.pgn
wget http://www.chess88.net/pgn/tatagpa16.pgn
wget http://www.chess88.net/pgn/charmhl16.pgn
wget http://www.chess88.net/pgn/tatagpb16.pgn
wget http://www.chess88.net/pgn/gibralmast16.pgn
wget http://www.chess88.net/pgn/moscoopa16.pgn
wget http://www.chess88.net/pgn/gibraltb16.pgn
wget http://www.chess88.net/pgn/tehranwgp16.pgn
wget http://www.chess88.net/pgn/zurichccob16.pgn
wget http://www.chess88.net/pgn/zurichccm16.pgn
wget http://www.chess88.net/pgn/zurichcc16.pgn
wget http://www.chess88.net/pgn/aeroflotopa16.pgn
wget http://www.chess88.net/pgn/zurichccb16.pgn
wget http://www.chess88.net/pgn/wchw16.pgn
wget http://www.chess88.net/pgn/reykop16.pgn
wget http://www.chess88.net/pgn/wchcand16.pgn
wget http://www.chess88.net/pgn/norwayq16.pgn
wget http://www.chess88.net/pgn/asiannatcup16.pgn
wget http://www.chess88.net/pgn/asiannatcupw16.pgn
wget http://www.chess88.net/pgn/tchchn16.pgn
wget http://www.chess88.net/pgn/chusa16.pgn
wget http://www.chess88.net/pgn/chchn16.pgn
wget http://www.chess88.net/pgn/chusaw16.pgn
wget http://www.chess88.net/pgn/chchnw16.pgn
wget http://www.chess88.net/pgn/batumiwgp16.pgn
wget http://www.chess88.net/pgn/norway16.pgn
wget http://www.chess88.net/pgn/ultblitz16.pgn
wget http://www.chess88.net/pgn/bund1516.pgn
wget http://www.chess88.net/pgn/dingsom16.pgn
wget http://www.chess88.net/pgn/hasselbop16.pgn
wget http://www.chess88.net/pgn/tchrusm16.pgn
wget http://www.chess88.net/pgn/nakhp16.pgn
wget http://www.chess88.net/pgn/cheurind16.pgn
wget http://www.chess88.net/pgn/gashmem16.pgn
wget http://www.chess88.net/pgn/asiancont16.pgn
wget http://www.chess88.net/pgn/tchfra16.pgn
wget http://www.chess88.net/pgn/asiancontw16.pgn
wget http://www.chess88.net/pgn/cheurw16.pgn
wget http://www.chess88.net/pgn/zalaop16.pgn
wget http://www.chess88.net/pgn/chisl16.pgn
wget http://www.chess88.net/pgn/kurnmem16.pgn
wget http://www.chess88.net/pgn/utrechtop16.pgn
wget http://www.chess88.net/pgn/gashmemtb16.pgn
wget http://www.chess88.net/pgn/cez16.pgn
wget http://www.chess88.net/pgn/capmeme16.pgn
wget http://www.chess88.net/pgn/chnrusm16.pgn
wget http://www.chess88.net/pgn/gctrapparis16.pgn
wget http://www.chess88.net/pgn/chnrusw16.pgn
wget http://www.chess88.net/pgn/gctbliparis16.pgn
wget http://www.chess88.net/pgn/gctrapynm16.pgn
wget http://www.chess88.net/pgn/gctbliynm16.pgn
wget http://www.chess88.net/pgn/voronop16.pgn
wget http://www.chess88.net/pgn/chrushl16.pgn
wget http://www.chess88.net/pgn/vidmarmem16.pgn
wget http://www.chess88.net/pgn/chrushlw16.pgn
wget http://www.chess88.net/pgn/edmontgm16.pgn
wget http://www.chess88.net/pgn/asrianmem16.pgn
wget http://www.chess88.net/pgn/chengduwgp16.pgn
wget http://www.chess88.net/pgn/haindan16.pgn
wget http://www.chess88.net/pgn/dort16.pgn
wget http://www.chess88.net/pgn/polumem16.pgn
wget http://www.chess88.net/pgn/bilbaomast16.pgn
wget http://www.chess88.net/pgn/najmema16.pgn
wget http://www.chess88.net/pgn/dinggrim16.pgn
wget http://www.chess88.net/pgn/ghentop16.pgn
wget http://www.chess88.net/pgn/czechopa16.pgn
wget http://www.chess88.net/pgn/lakesevan16.pgn
wget http://www.chess88.net/pgn/poikgm16.pgn
wget http://www.chess88.net/pgn/bielmr16.pgn
wget http://www.chess88.net/pgn/chgbr16.pgn
wget http://www.chess88.net/pgn/bielmc16.pgn
wget http://www.chess88.net/pgn/dutchop16.pgn
wget http://www.chess88.net/pgn/tchtursup16.pgn
wget http://www.chess88.net/pgn/xtraconop16.pgn
wget http://www.chess88.net/pgn/chnteamm16.pgn
wget http://www.chess88.net/pgn/andop16.pgn
wget http://www.chess88.net/pgn/sinqcup16.pgn
wget http://www.chess88.net/pgn/chesp16.pgn
wget http://www.chess88.net/pgn/hzop16.pgn
wget http://www.chess88.net/pgn/rigatechopa16.pgn
wget http://www.chess88.net/pgn/wjun16.pgn
wget http://www.chess88.net/pgn/chfra16.pgn
wget http://www.chess88.net/pgn/wjung16.pgn
wget http://www.chess88.net/pgn/chfraw16.pgn
wget http://www.chess88.net/pgn/manhemgm16.pgn
wget http://www.chess88.net/pgn/washint16.pgn
wget http://www.chess88.net/pgn/santsop16.pgn
wget http://www.chess88.net/pgn/chned16.pgn
wget http://www.chess88.net/pgn/abudmast16.pgn
wget http://www.chess88.net/pgn/chnedw16.pgn
wget http://www.chess88.net/pgn/stosumrap16.pgn
wget http://www.chess88.net/pgn/olym16.pgn
wget http://www.chess88.net/pgn/talmemb16.pgn
wget http://www.chess88.net/pgn/olymw16.pgn
wget http://www.chess88.net/pgn/tchpole16.pgn
wget http://www.chess88.net/pgn/talmem16.pgn
wget http://www.chess88.net/pgn/tchesphon16.pgn
wget http://www.chess88.net/pgn/osloop16.pgn
wget http://www.chess88.net/pgn/iommast16.pgn
wget http://www.chess88.net/pgn/navhammatchc16.pgn
wget http://www.chess88.net/pgn/chrusrap16.pgn
wget http://www.chess88.net/pgn/navhammatchr16.pgn
wget http://www.chess88.net/pgn/chrusrapw16.pgn
wget http://www.chess88.net/pgn/basamrom16.pgn
wget http://www.chess88.net/pgn/chigmem16.pgn
wget http://www.chess88.net/pgn/hwpmast16.pgn
wget http://www.chess88.net/pgn/timurrap16.pgn
wget http://www.chess88.net/pgn/hoogop16.pgn
wget http://www.chess88.net/pgn/chrus16.pgn
wget http://www.chess88.net/pgn/hoogsh16.pgn
wget http://www.chess88.net/pgn/chrusw16.pgn
wget http://www.chess88.net/pgn/karpovtropp16.pgn
wget http://www.chess88.net/pgn/barcgm16.pgn
wget http://www.chess88.net/pgn/chnordic16.pgn
wget http://www.chess88.net/pgn/charm116.pgn
wget http://www.chess88.net/pgn/ecc16.pgn
wget http://www.chess88.net/pgn/champshow6016.pgn
wget http://www.chess88.net/pgn/eccw16.pgn
wget http://www.chess88.net/pgn/wch16.pgn
wget http://www.chess88.net/pgn/britrap16.pgn
wget http://www.chess88.net/pgn/chindnp16.pgn
wget http://www.chess88.net/pgn/ugragovcup16.pgn
wget http://www.chess88.net/pgn/kmwgp16.pgn
wget http://www.chess88.net/pgn/kingsrm16.pgn
wget http://www.chess88.net/pgn/wchr16.pgn
wget http://www.chess88.net/pgn/kingsrr16.pgn
wget http://www.chess88.net/pgn/chukr16.pgn
wget http://www.chess88.net/pgn/loncc16.pgn
wget http://www.chess88.net/pgn/chisr16.pgn
wget http://www.chess88.net/pgn/lonccop16.pgn
wget http://www.chess88.net/pgn/eurrap16.pgn
wget http://www.chess88.net/pgn/eurbli16.pgn
wget http://www.chess88.net/pgn/lonccsrap16.pgn
wget http://www.chess88.net/pgn/weiyirappm16.pgn
wget http://www.chess88.net/pgn/gronop16.pgn
wget http://www.chess88.net/pgn/sunwayop16.pgn
wget http://www.chess88.net/pgn/wrap16.pgn
wget http://www.chess88.net/pgn/wrapw16.pgn
wget http://www.chess88.net/pgn/wbli16.pgn
wget http://www.chess88.net/pgn/wbliw16.pgn
wget http://www.chess88.net/pgn/tatagpa17.pgn
wget http://www.chess88.net/pgn/delhiop17.pgn
wget http://www.chess88.net/pgn/tatagpb17.pgn
wget http://www.chess88.net/pgn/margmem17.pgn
wget http://www.chess88.net/pgn/gibralmast17.pgn
wget http://www.chess88.net/pgn/gibraltb17.pgn
wget http://www.chess88.net/pgn/wchwko17.pgn
wget http://www.chess88.net/pgn/sharjgp17.pgn
wget http://www.chess88.net/pgn/aeroflotopa17.pgn
wget http://www.chess88.net/pgn/chnindsummit17.pgn
wget http://www.chess88.net/pgn/hdbank17.pgn
wget http://www.chess88.net/pgn/shenzhenm17.pgn
wget http://www.chess88.net/pgn/chpol17.pgn
wget http://www.chess88.net/pgn/sharjmast17.pgn
wget http://www.chess88.net/pgn/chusa17.pgn
wget http://www.chess88.net/pgn/chusaw17.pgn
wget http://www.chess88.net/pgn/dubaiop17.pgn
wget http://www.chess88.net/pgn/houivam17.pgn
wget http://www.chess88.net/pgn/chusatb17.pgn
wget http://www.chess88.net/pgn/zurichcc17.pgn
wget http://www.chess88.net/pgn/cheurw17.pgn
wget http://www.chess88.net/pgn/zurichccbli17.pgn
wget http://www.chess88.net/pgn/grenkeop17.pgn
wget http://www.chess88.net/pgn/zurichccop17.pgn
wget http://www.chess88.net/pgn/grenke17.pgn
wget http://www.chess88.net/pgn/poikgm17.pgn
wget http://www.chess88.net/pgn/reykop17.pgn
wget http://www.chess88.net/pgn/tchchn17.pgn
wget http://www.chess88.net/pgn/gashmem17.pgn
wget http://www.chess88.net/pgn/chchn17.pgn
wget http://www.chess88.net/pgn/bund1617.pgn
wget http://www.chess88.net/pgn/chchnw17.pgn
wget http://www.chess88.net/pgn/tchrusm17.pgn
wget http://www.chess88.net/pgn/asiancont17.pgn
wget http://www.chess88.net/pgn/tchrusw17.pgn
wget http://www.chess88.net/pgn/asiancontw17.pgn
wget http://www.chess88.net/pgn/tchrusmaj17.pgn
wget http://www.chess88.net/pgn/moscgp17.pgn
wget http://www.chess88.net/pgn/sige17.pgn
wget http://www.chess88.net/pgn/chisl17.pgn
wget http://www.chess88.net/pgn/zalaop17.pgn
wget http://www.chess88.net/pgn/tchfra17.pgn
wget http://www.chess88.net/pgn/norwayb17.pgn
wget http://www.chess88.net/pgn/cheurind17.pgn
wget http://www.chess88.net/pgn/norway17.pgn
wget http://www.chess88.net/pgn/worldteam17.pgn
wget http://www.chess88.net/pgn/gctrapparis17.pgn
wget http://www.chess88.net/pgn/worldteamw17.pgn
wget http://www.chess88.net/pgn/asrianmem17.pgn
wget http://www.chess88.net/pgn/gctbliparis17.pgn
wget http://www.chess88.net/pgn/gctrapynm17.pgn
wget http://www.chess88.net/pgn/gctbliynm17.pgn
wget http://www.chess88.net/pgn/danzhou17.pgn
wget http://www.chess88.net/pgn/chrushl17.pgn
wget http://www.chess88.net/pgn/leon17.pgn
wget http://www.chess88.net/pgn/chrushlw17.pgn
wget http://www.chess88.net/pgn/genevagp17.pgn
wget http://www.chess88.net/pgn/dort17.pgn
wget http://www.chess88.net/pgn/chnrusgm17.pgn
wget http://www.chess88.net/pgn/bielgm17.pgn
wget http://www.chess88.net/pgn/czechopa17.pgn
wget http://www.chess88.net/pgn/sinqcup17.pgn
wget http://www.chess88.net/pgn/chgbr17.pgn
wget http://www.chess88.net/pgn/germmast17.pgn
wget http://www.chess88.net/pgn/dingiri17.pgn
wget http://www.chess88.net/pgn/stlrap17.pgn
wget http://www.chess88.net/pgn/abudmast17.pgn
wget http://www.chess88.net/pgn/stlbli17.pgn
wget http://www.chess88.net/pgn/wcup17.pgn
wget http://www.chess88.net/pgn/iommast17.pgn
wget http://www.chess88.net/pgn/tchrusrap17.pgn
wget http://www.chess88.net/pgn/ecc17.pgn
wget http://www.chess88.net/pgn/tchrusrapw17.pgn
wget http://www.chess88.net/pgn/eccw17.pgn
wget http://www.chess88.net/pgn/champshow3017.pgn
wget http://www.chess88.net/pgn/champshow2017.pgn
wget http://www.chess88.net/pgn/champshow1017.pgn
wget http://www.chess88.net/pgn/champshowcd3017.pgn
wget http://www.chess88.net/pgn/champshow517.pgn
wget http://www.chess88.net/pgn/champshowcd2017.pgn
wget http://www.chess88.net/pgn/champshowcd517.pgn
wget http://www.chess88.net/pgn/champshowcd1017.pgn
wget http://www.chess88.net/pgn/kingsrap17.pgn
wget http://www.chess88.net/pgn/barcgm17.pgn
wget http://www.chess88.net/pgn/kingsbl17.pgn
wget http://www.chess88.net/pgn/kingsrapw17.pgn
wget http://www.chess88.net/pgn/pdmgp17.pgn
wget http://www.chess88.net/pgn/kingsblw17.pgn
wget http://www.chess88.net/pgn/loncc17.pgn
wget http://www.chess88.net/pgn/chita17.pgn
wget http://www.chess88.net/pgn/chgbrko17.pgn
wget http://www.chess88.net/pgn/chrus17.pgn
wget http://www.chess88.net/pgn/lonccop17.pgn
wget http://www.chess88.net/pgn/chrusw17.pgn
wget http://www.chess88.net/pgn/loncctb17.pgn
wget http://www.chess88.net/pgn/chrustb17.pgn
wget http://www.chess88.net/pgn/hetenmemgm17.pgn
wget http://www.chess88.net/pgn/chruswtb17.pgn
wget http://www.chess88.net/pgn/hetenmemim17.pgn
wget http://www.chess88.net/pgn/eurrap17.pgn
wget http://www.chess88.net/pgn/wrap17.pgn
wget http://www.chess88.net/pgn/eurbli17.pgn
wget http://www.chess88.net/pgn/wraptb17.pgn
wget http://www.chess88.net/pgn/wrapw17.pgn
wget http://www.chess88.net/pgn/wbli17.pgn
wget http://www.chess88.net/pgn/wbliw17.pgn
wget http://www.chess88.net/pgn/gronop17.pgn
wget http://www.chess88.net/pgn/hastm17.pgn
wget http://www.chess88.net/pgn/gronm17.pgn
wget http://www.chess88.net/pgn/riltcup1718.pgn
wget http://www.chess88.net/pgn/weiyinav1718.pgn
wget http://www.chess88.net/pgn/margmem18.pgn
wget http://www.chess88.net/pgn/tatagpa18.pgn
wget http://www.chess88.net/pgn/delhiop18.pgn
wget http://www.chess88.net/pgn/tatagpb18.pgn
wget http://www.chess88.net/pgn/gibralmast18.pgn
wget http://www.chess88.net/pgn/tatagpatb18.pgn
wget http://www.chess88.net/pgn/gibralmasttb18.pgn
wget http://www.chess88.net/pgn/verganicup18.pgn
wget http://www.chess88.net/pgn/houkarrap18.pgn
wget http://www.chess88.net/pgn/aeroflotopa18.pgn
wget http://www.chess88.net/pgn/bataviagm18.pgn
wget http://www.chess88.net/pgn/talmemr18.pgn
wget http://www.chess88.net/pgn/talmemb18.pgn
wget http://www.chess88.net/pgn/stlsprclasa18.pgn
wget http://www.chess88.net/pgn/reykop18.pgn
wget http://www.chess88.net/pgn/wchcand18.pgn
wget http://www.chess88.net/pgn/cheurind18.pgn
wget http://www.chess88.net/pgn/grenkecc18.pgn
wget http://www.chess88.net/pgn/dubaiop18.pgn
wget http://www.chess88.net/pgn/jerseyop18.pgn
wget http://www.chess88.net/pgn/cheurw18.pgn
wget http://www.chess88.net/pgn/tchchn18.pgn
wget http://www.chess88.net/pgn/sharjmast18.pgn
wget http://www.chess88.net/pgn/chchn18.pgn
wget http://www.chess88.net/pgn/chusa18.pgn
wget http://www.chess88.net/pgn/chchnw18.pgn
wget http://www.chess88.net/pgn/chusaw18.pgn
wget http://www.chess88.net/pgn/gashmem18.pgn
wget http://www.chess88.net/pgn/chusatbw18.pgn
wget http://www.chess88.net/pgn/tchrusp18.pgn
wget http://www.chess88.net/pgn/nakhop18.pgn
wget http://www.chess88.net/pgn/tchrusw18.pgn
wget http://www.chess88.net/pgn/wchw18.pgn
wget http://www.chess88.net/pgn/sige18.pgn
wget http://www.chess88.net/pgn/tchhun1718.pgn
wget http://www.chess88.net/pgn/capmeme18.pgn
wget http://www.chess88.net/pgn/kolkop18.pgn
wget http://www.chess88.net/pgn/stlsumclasa18.pgn
wget http://www.chess88.net/pgn/stlsumclasb18.pgn
wget http://www.chess88.net/pgn/stlsumclasatb18.pgn
wget http://www.chess88.net/pgn/poikgm18.pgn
wget http://www.chess88.net/pgn/norwayb18.pgn
wget http://www.chess88.net/pgn/tchfra18.pgn
wget http://www.chess88.net/pgn/norway18.pgn
wget http://www.chess88.net/pgn/amercont18.pgn
wget http://www.chess88.net/pgn/gctrapynm18.pgn
wget http://www.chess88.net/pgn/cez18.pgn
wget http://www.chess88.net/pgn/gctbliynm18.pgn
wget http://www.chess88.net/pgn/apeldweek18.pgn
wget http://www.chess88.net/pgn/gctrapparis18.pgn
wget http://www.chess88.net/pgn/gctbliparis18.pgn
wget http://www.chess88.net/pgn/asrianmem18.pgn
wget http://www.chess88.net/pgn/chrushl18.pgn
wget http://www.chess88.net/pgn/pulaop18.pgn
wget http://www.chess88.net/pgn/chrushlw18.pgn
wget http://www.chess88.net/pgn/japhetcup18.pgn
wget http://www.chess88.net/pgn/leon18.pgn
wget http://www.chess88.net/pgn/chned18.pgn
wget http://www.chess88.net/pgn/batmuncup18.pgn
wget http://www.chess88.net/pgn/chnedw18.pgn
wget http://www.chess88.net/pgn/dort18.pgn
wget http://www.chess88.net/pgn/czechopa18.pgn
wget http://www.chess88.net/pgn/xtraconop18.pgn
wget http://www.chess88.net/pgn/bielgm18.pgn
wget http://www.chess88.net/pgn/haindan18.pgn
wget http://www.chess88.net/pgn/tchtursup18.pgn
wget http://www.chess88.net/pgn/chgbr18.pgn
wget http://www.chess88.net/pgn/rigatechopa18.pgn
wget http://www.chess88.net/pgn/chgbrtb18.pgn
wget http://www.chess88.net/pgn/abudmast18.pgn
wget http://www.chess88.net/pgn/stlrap18.pgn
wget http://www.chess88.net/pgn/tandzam18.pgn
wget http://www.chess88.net/pgn/dingtopm18.pgn
wget http://www.chess88.net/pgn/stlbli18.pgn
wget http://www.chess88.net/pgn/inarkweim18.pgn
wget http://www.chess88.net/pgn/sinqcup18.pgn
wget http://www.chess88.net/pgn/chfra18.pgn
wget http://www.chess88.net/pgn/chrus18.pgn
wget http://www.chess88.net/pgn/inarkweir18.pgn
wget http://www.chess88.net/pgn/chrusw18.pgn
wget http://www.chess88.net/pgn/chfratb18.pgn
wget http://www.chess88.net/pgn/sinqcupgcttb18.pgn
wget http://www.chess88.net/pgn/wjun18.pgn
wget http://www.chess88.net/pgn/olym18.pgn
wget http://www.chess88.net/pgn/wjung18.pgn
wget http://www.chess88.net/pgn/olymw18.pgn
wget http://www.chess88.net/pgn/ecc18.pgn
wget http://www.chess88.net/pgn/tchpole18.pgn
wget http://www.chess88.net/pgn/eccw18.pgn
wget http://www.chess88.net/pgn/iommast18.pgn
wget http://www.chess88.net/pgn/wchwko18.pgn
wget http://www.chess88.net/pgn/shenzhenm18.pgn
wget http://www.chess88.net/pgn/tataindiarap18.pgn
wget http://www.chess88.net/pgn/wch18.pgn
wget http://www.chess88.net/pgn/tataindiabli18.pgn
wget http://www.chess88.net/pgn/stlwintclasa18.pgn
wget http://www.chess88.net/pgn/stlwintclasb18.pgn
wget http://www.chess88.net/pgn/wchr18.pgn
wget http://www.chess88.net/pgn/ugragovcup18.pgn
wget http://www.chess88.net/pgn/loncc18.pgn
wget http://www.chess88.net/pgn/chgbrko18.pgn
wget http://www.chess88.net/pgn/lonccop18.pgn
wget http://www.chess88.net/pgn/sunwayop18.pgn
wget http://www.chess88.net/pgn/wrap18.pgn
wget http://www.chess88.net/pgn/binhaicup18.pgn
wget http://www.chess88.net/pgn/wrapw18.pgn
wget http://www.chess88.net/pgn/hastm1819.pgn
wget http://www.chess88.net/pgn/wbli18.pgn
wget http://www.chess88.net/pgn/wbliw18.pgn
wget http://www.chess88.net/pgn/tatagpa19.pgn
wget http://www.chess88.net/pgn/tatagpb19.pgn
wget http://www.chess88.net/pgn/gibralmast19.pgn
wget http://www.chess88.net/pgn/cairnscup19.pgn
wget http://www.chess88.net/pgn/aeroflotopa19.pgn
wget http://www.chess88.net/pgn/champshowr19.pgn
wget http://www.chess88.net/pgn/bunrat19.pgn
wget http://www.chess88.net/pgn/champshowb19.pgn
wget http://www.chess88.net/pgn/worldteam19.pgn
wget http://www.chess88.net/pgn/worldteamw19.pgn
wget http://www.chess88.net/pgn/bataviagm19.pgn
wget http://www.chess88.net/pgn/praguemast19.pgn
wget http://www.chess88.net/pgn/stlsprclasa19.pgn
wget http://www.chess88.net/pgn/praguechall19.pgn
wget http://www.chess88.net/pgn/chusa19.pgn
wget http://www.chess88.net/pgn/cheurind19.pgn
wget http://www.chess88.net/pgn/chusaw19.pgn
wget http://www.chess88.net/pgn/gashmem19.pgn
wget http://www.chess88.net/pgn/dubaiop19.pgn
wget http://www.chess88.net/pgn/reykop19.pgn
wget http://www.chess88.net/pgn/tchchn19.pgn
wget http://www.chess88.net/pgn/shenzhenm19.pgn
wget http://www.chess88.net/pgn/grenkecc19.pgn
wget http://www.chess88.net/pgn/chchn19.pgn
wget http://www.chess88.net/pgn/sige19.pgn
wget http://www.chess88.net/pgn/chchnw19.pgn
wget http://www.chess88.net/pgn/tchrusp19.pgn
wget http://www.chess88.net/pgn/capmeme19.pgn
wget http://www.chess88.net/pgn/tchrushl19.pgn
wget http://www.chess88.net/pgn/ivoryrap19.pgn
wget http://www.chess88.net/pgn/tchrusw19.pgn
wget http://www.chess88.net/pgn/ivorybli19.pgn
wget http://www.chess88.net/pgn/tchfra19.pgn
wget http://www.chess88.net/pgn/lindabbey19.pgn
wget http://www.chess88.net/pgn/moscowgp19.pgn
wget http://www.chess88.net/pgn/imsarap19.pgn
wget http://www.chess88.net/pgn/imsabli19.pgn
wget http://www.chess88.net/pgn/imsarapw19.pgn
wget http://www.chess88.net/pgn/imsabliw19.pgn
wget http://www.chess88.net/pgn/wchwcand19.pgn
wget http://www.chess88.net/pgn/norwayb19.pgn
wget http://www.chess88.net/pgn/norway19.pgn
wget http://www.chess88.net/pgn/norwaya19.pgn
wget http://www.chess88.net/pgn/poikgm19.pgn
wget http://www.chess88.net/pgn/crogct19.pgn
wget http://www.chess88.net/pgn/chrushl19.pgn
wget http://www.chess88.net/pgn/danzhougm19.pgn
wget http://www.chess88.net/pgn/chrushlw19.pgn
wget http://www.chess88.net/pgn/chnteamm19.pgn
wget http://www.chess88.net/pgn/stlsumclasa19.pgn
wget http://www.chess88.net/pgn/chnteamw19.pgn
wget http://www.chess88.net/pgn/stlsumclasb19.pgn
wget http://www.chess88.net/pgn/netanyamast19.pgn
wget http://www.chess88.net/pgn/stlsumclasc19.pgn
wget http://www.chess88.net/pgn/netanyaop19.pgn
wget http://www.chess88.net/pgn/dort19.pgn
wget http://www.chess88.net/pgn/dorthk19.pgn
wget http://www.chess88.net/pgn/dortop19.pgn
wget http://www.chess88.net/pgn/rigagp19.pgn
wget http://www.chess88.net/pgn/xtraconop19.pgn
wget http://www.chess88.net/pgn/gctrapparis19.pgn
wget http://www.chess88.net/pgn/bielgm19.pgn
wget http://www.chess88.net/pgn/hunanopa19.pgn
wget http://www.chess88.net/pgn/bielop19.pgn
wget http://www.chess88.net/pgn/gctbliparis19.pgn
wget http://www.chess88.net/pgn/chgbr19.pgn
wget http://www.chess88.net/pgn/abudmast19.pgn
wget http://www.chess88.net/pgn/stlrap19.pgn
wget http://www.chess88.net/pgn/chesscomjsp19.pgn
wget http://www.chess88.net/pgn/stlbli19.pgn
wget http://www.chess88.net/pgn/chrus19.pgn
wget http://www.chess88.net/pgn/sinqcup19.pgn
wget http://www.chess88.net/pgn/chrusw19.pgn
wget http://www.chess88.net/pgn/sinqcuptb19.pgn
wget http://www.chess88.net/pgn/chruswtb19.pgn
wget http://www.chess88.net/pgn/wcup19.pgn
wget http://www.chess88.net/pgn/skolwgp19.pgn
wget http://www.chess88.net/pgn/stlouisfalla19.pgn
wget http://www.chess88.net/pgn/iommast19.pgn
wget http://www.chess88.net/pgn/chigmem19.pgn
wget http://www.chess88.net/pgn/wjun19.pgn
wget http://www.chess88.net/pgn/tcheur19.pgn
wget http://www.chess88.net/pgn/wjung19.pgn
wget http://www.chess88.net/pgn/tcheurw19.pgn
wget http://www.chess88.net/pgn/hamburggp19.pgn
wget http://www.chess88.net/pgn/buchrap19.pgn
wget http://www.chess88.net/pgn/stlwintclasa19.pgn
wget http://www.chess88.net/pgn/buchbli19.pgn
wget http://www.chess88.net/pgn/buchtb19.pgn
wget http://www.chess88.net/pgn/tataindrap19.pgn
wget http://www.chess88.net/pgn/loncc19.pgn
wget http://www.chess88.net/pgn/tataindbli19.pgn
wget http://www.chess88.net/pgn/chgbrko19.pgn
wget http://www.chess88.net/pgn/lonccop19.pgn
wget http://www.chess88.net/pgn/chgbrkop19.pgn
wget http://www.chess88.net/pgn/jerugp19.pgn
wget http://www.chess88.net/pgn/monacowgp19.pgn
wget http://www.chess88.net/pgn/sunwayop19.pgn
wget http://www.chess88.net/pgn/wrap19.pgn
wget http://www.chess88.net/pgn/wbli19.pgn
wget http://www.chess88.net/pgn/wrapw19.pgn
wget http://www.chess88.net/pgn/wblitb19.pgn
wget http://www.chess88.net/pgn/wrapwtb19.pgn
wget http://www.chess88.net/pgn/wchw20.pgn
wget http://www.chess88.net/pgn/hastm1920.pgn
wget http://www.chess88.net/pgn/tatagpa20.pgn
wget http://www.chess88.net/pgn/gibralmast20.pgn
wget http://www.chess88.net/pgn/tatagpb20.pgn
wget http://www.chess88.net/pgn/gibralmasttb20.pgn
wget http://www.chess88.net/pgn/wchwtb20.pgn
